// Textes du chantier C8 : tableau « Engagement et participation »
// (/pilotage/engagement), chiffres corrigés du tableau de pilotage et export
// CSV. Pages du personnel : vouvoiement. Chaque chiffre a sa phrase de lecture
// (« … · lecture ») qui dit exactement ce qu'il compte.
import { creerTextes } from "./index";

export const t = creerTextes({
  // ── En-tête et filtres ──
  "page.etiquette": "Pilotage · Engagement et participation",
  "page.titre": "Engagement et participation",
  "page.sousTitre":
    "Ce que font vraiment les étudiants : apprendre sur leur téléphone, suivre les directs, travailler entre les cours. Chaque chiffre dit ce qu'il compte.",
  "page.export": "Exporter par classe (CSV)",
  "page.recalculer": "Recalculer",
  "page.calculeLe": "Calculé à {heure}, gardé 10 minutes",
  "filtre.periode": "Période",
  "filtre.jours": "{n} jours",
  "filtre.campus": "Campus",
  "filtre.tousCampus": "Tous les campus",
  "filtre.classe": "Classe",
  "filtre.toutesClasses": "Toutes les classes",
  "page.effectif": "{n} étudiants dans ce groupe",
  "page.tropPetit.titre": "Moins de 5 étudiants dans ce groupe.",
  "page.tropPetit.texte":
    "Aucun chiffre n'est affiché sous 5 étudiants : un taux désignerait des personnes. Choisissez un groupe plus large (le campus, ou toutes les classes).",
  "page.mesureDepuis":
    "L'ouverture du campus est enregistrée jour par jour depuis le {date}. Avant cette date, seules les actions d'apprentissage sont connues : les chiffres d'ouverture plus anciens sont des minimums.",
  "page.mesureAucune":
    "L'ouverture du campus n'est pas encore enregistrée jour par jour (elle commence à la mise en ligne de ce tableau) : pour l'instant, seules les actions d'apprentissage sont connues.",
  "commun.pasEncoreMesure": "Pas encore mesuré",
  "commun.pasEncoreMesure.texte": "Ces chiffres apparaîtront dès que les fonctions correspondantes seront en ligne : rien n'est compté à zéro en attendant.",
  "commun.effectifPetit": "moins de 5 : pas de taux",
  "commun.surN": "{n} sur {sur}",
  "commun.aucun": "Rien à mesurer sur la période.",
  "commun.voirChiffres": "Voir les chiffres",

  // ── 1. Indicateur principal ──
  "principal.titre": "Jours d'apprentissage par étudiant et par semaine",
  "principal.detail": "médiane de la semaine du {date} · cible : 3 jours",
  "principal.lecture":
    "Un jour compte quand l'étudiant fait au moins une action d'apprentissage : présence suivie à un direct, copie rendue, interrogation, leçon terminée, replay, question ou vote pendant un direct, et, dès qu'elles seront en ligne, révision, cours complet et objectif du jour. Ouvrir le campus ne suffit jamais. Semaines entières, du lundi au dimanche, pour les étudiants inscrits avant le lundi ; la semaine en cours est provisoire.",
  "principal.auMoins3": "Au moins 3 jours",
  "principal.auMoins1": "Au moins 1 jour",
  "principal.enCours": "en cours",
  "principal.cible": "cible 3",
  "principal.graphique": "Médiane des jours d'apprentissage, semaine par semaine",

  // ── 2. Téléphone et régularité ──
  "regularite.titre": "Téléphone et régularité",
  "actifs.aujourdhui": "Aujourd'hui",
  "actifs.j7": "7 jours",
  "actifs.j30": "30 jours",
  "actifs.appris": "ont appris",
  "actifs.venus": "{n} venus en tout",
  "actifs.lecture":
    "Grand chiffre : étudiants qui ont fait au moins une action d'apprentissage. « Venus » : ceux qui ont ouvert le campus, avec ou sans action. Comptés en jours réels (heure d'Abidjan), une seule fois chacun.",
  "sansCours.titre": "Jours sans cours",
  "sansCours.lecture":
    "Part des journées d'étudiants SANS direct de leurs cours où ils ont fait une action d'apprentissage (jours complets de la période). C'est le chiffre de l'habitude : cible 30 % après 4 semaines, 50 % après 8.",
  "avecCours.titre": "Jours de cours",
  "avecCours.lecture": "Même calcul les jours où l'un de leurs cours avait un direct. À lire à part : la présence au direct y compte déjà.",
  "courbe.titre": "Étudiants actifs jour par jour",
  "courbe.lecture":
    "Hauteur totale : étudiants qui ont ouvert le campus ce jour-là (enregistré jour par jour depuis la mise en ligne). Bleu : action d'apprentissage un jour de cours pour eux ; orange : action un jour sans cours ; gris : ouverture sans action. Touchez un jour pour son détail.",
  "courbe.cours": "Action, jour de cours",
  "courbe.sansCours": "Action, jour sans cours",
  "courbe.ouvertSeul": "Ouverture sans action",
  "courbe.detail": "{jour} : {ac} actions un jour de cours, {asc} un jour sans cours, {o} ouvertures en tout",
  "courbe.detailSansOuverture": "{jour} : {ac} actions un jour de cours, {asc} un jour sans cours (ouverture non mesurée)",
  "courbe.colonneJour": "Jour",
  "courbe.colonneOuverts": "Ouvertures",
  "courbe.colonneInscrits": "Inscrits",
  "courbe.colonneAvecCours": "Avec un direct",
  "plateformes.titre": "Sur quel appareil ?",
  "plateformes.lecture":
    "Journées d'étudiants passées sur le campus, selon l'appareil. Un jour passé en partie sur le téléphone compte comme un jour sur téléphone. « Inconnu » : ancienne version de l'application, sans l'information.",
  "plateformes.android_app": "Appli Android",
  "plateformes.installee": "Appli installée",
  "plateformes.mobile": "Navigateur du téléphone",
  "plateformes.ordinateur": "Ordinateur",
  "plateformes.inconnue": "Inconnu",
  "plateformes.telephone": "{n} % des journées sur téléphone",
  "plateformes.vide": "Aucune journée enregistrée sur la période pour l'instant.",
  "retour.titre": "Retour après le premier jour",
  "retour.lecture":
    "Par semaine de création du compte : part des étudiants revenus le lendemain de leur premier jour (J1), puis entre le 7e et le 13e jour (J7). « Revenu » : une ouverture du campus ou une action d'apprentissage. ≈ : premier jour antérieur à l'enregistrement jour par jour, le chiffre est un minimum.",
  "retour.semaine": "Inscrits la semaine du",
  "retour.inscrits": "Comptes",
  "retour.venus": "Venus",
  "retour.j1": "J1",
  "retour.j7": "J7",
  "revenus.titre": "Revenus après leur premier jour",
  "revenus.lecture": "Étudiants vus sur le campus au moins deux jours différents (ouverture ou action), depuis leur inscription.",

  // ── 3. Directs ──
  "directs.titre": "Directs : présence et participation",
  "presence.titre": "Présence aux directs, en trois états",
  "presence.lecture":
    "Chaque étudiant attendu à chaque séance tenue de la période. Présent : émargé en salle (QR ou code) ou suivi en ligne jusqu'au seuil de 70 %. Absent : sa salle a été émargée sans lui, ou il ne peut suivre qu'en ligne. Inconnu : personne n'a été émargé dans la salle de son campus ; ce n'est jamais compté comme une absence.",
  "presence.presents": "Présents",
  "presence.absents": "Absents",
  "presence.inconnus": "Inconnus",
  "presence.tauxConnu": "{n} % de présents là où la présence est connue",
  "presence.partInconnue": "{n} % de présence inconnue : faites émarger les salles",
  "emargement.titre": "Séances émargées par campus",
  "emargement.lecture":
    "Une salle est émargée quand au moins un étudiant y a scanné le QR de l'écran ou a été pointé par le responsable. Sans émargement, la présence de tout le campus reste inconnue : les campus en tête de liste doivent faire émarger.",
  "emargement.seances": "{e} séances émargées sur {n}",
  "emargement.incidents": "dont {n} avec un incident de salle",
  "emargement.emarges": "{n} % des étudiants attendus émargés",
  "suivi.titre": "Ont suivi au moins un direct",
  "suivi.lecture": "Étudiants émargés en salle, ou qui ont suivi en ligne au moins 30 minutes (ou la moitié d'une séance plus courte), sur ceux qui avaient au moins un direct.",
  "entonnoir.titre": "Entonnoir, séance par séance",
  "entonnoir.lecture":
    "Attendus → venus (en salle ou en ligne) → ont suivi (30 minutes ou la moitié) → au seuil officiel de 70 % en ligne → ont participé (question, vote, sondage, message, main levée). Les campus et les classes de moins de 5 attendus ne sont pas détaillés. Mêmes règles que le bilan de séance.",
  "entonnoir.attendus": "Attendus",
  "entonnoir.enSalle": "Émargés en salle",
  "entonnoir.enLigne": "Venus en ligne",
  "entonnoir.ontSuivi": "Ont suivi",
  "entonnoir.auSeuil": "Au seuil en ligne",
  "entonnoir.ontParticipe": "Ont participé",
  "entonnoir.presence": "{p} présents · {a} absents · {i} inconnus",
  "entonnoir.prevueLe": "prévue le {date}",
  "entonnoir.tenueLe": "tenue le {date}",
  "entonnoir.sondages": "{n} sondage(s)",
  "entonnoir.aucunSondage": "aucun sondage",
  "entonnoir.parCampus": "Par campus",
  "entonnoir.parClasse": "Par classe (5 attendus ou plus)",
  "entonnoir.salleEmargee": "salle émargée",
  "entonnoir.salleNonEmargee": "salle non émargée",
  "entonnoir.aucune": "Aucun direct tenu sur la période.",
  "entonnoir.detail": "Détail",
  "entonnoir.toutes": "Voir les {n} séances",

  // ── 4. Travail entre les cours ──
  "travail.titre": "Travail entre les cours",
  "travail.lecture":
    "Copies et interrogations « à ce jour » : un devoir compte dès sa publication, même s'il n'est pas encore échu ; le taux monte jusqu'à l'échéance. Un étudiant n'est attendu qu'aux devoirs de ses cours publiés après son arrivée.",
  "travail.copies": "Copies des devoirs des formateurs",
  "travail.interrogations": "Interrogations des formateurs",
  "travail.qcm_auto": "QCM automatiques (routine du soir)",
  "travail.exercices_auto": "Exercices automatiques (routine du soir)",
  "travail.rendus": "{n} rendus sur {sur} attendus",
  "travail.commences": "{n} commencés",
  "travail.ouverts": "{n} devoir(s) encore ouvert(s) : « à ce jour »",
  "travail.aucunDevoir": "Aucun devoir sur la période.",
  "replays.absents": "Replays ouverts par les absents",
  "replays.absents.lecture": "Absents connus à un direct (salle émargée sans eux) qui ont ouvert son replay.",
  "replays.inconnus": "Replays ouverts quand la présence est inconnue",
  "replays.inconnus.lecture": "À titre d'information : la plupart de ces étudiants étaient probablement en salle.",
  "revision.titre": "Révision du jour",
  "revision.reviseurs": "ont révisé ces 7 derniers jours",
  "revision.reponses": "{n} réponses par étudiant qui révise",
  "revision.boite3": "{n} % des cartes en boîte 3 ou plus (la mémoire tient)",
  "coursComplets.titre": "Cours complets ouverts",
  "coursComplets.lecture": "Étudiants qui ont ouvert au moins un cours complet sur la période.",
  "objectifs.titre": "Objectif du jour validé",
  "objectifs.lecture": "Objectifs validés sur l'ensemble des journées ouvrées complètes des inscrits (cible 30 %).",
  "semainesActives.titre": "Semaines actives",
  "semainesActives.lecture": "Étudiants dont la dernière semaine complète a atteint leur objectif de jours actifs (3 par défaut).",
  "coupe.titre": "Coupe des campus, 8 semaines",
  "coupe.lecture": "Taux de participation de chaque campus (au moins deux types d'actes dans la semaine), semaine par semaine.",

  // ── 5. Rappels ──
  "rappels.titre": "Rappels et étudiants joignables",
  "joignables.abonnes": "Téléphone abonné aux rappels",
  "joignables.abonnes.lecture": "Étudiants dont au moins un téléphone ou navigateur reçoit les rappels du campus (cible 70 %).",
  "joignables.essai": "Essai de rappel reçu",
  "joignables.essai.lecture": "Le rappel d'essai est arrivé et l'étudiant l'a confirmé sur son téléphone.",
  "joignables.email": "Adresse e-mail",
  "joignables.email.lecture": "Étudiants qui ont une adresse e-mail sur leur compte.",
  "joignables.parCampus": "Par campus",
  "joignables.parMarque": "Par marque de téléphone",
  "envois.titre": "Rappels envoyés",
  "envois.lecture":
    "Chaque décision d'envoi de la période : envoyé, différé au résumé suivant, bloqué par le plafond de 3 par jour, ou en échec. Ouverts : touchés dans les 24 h. Repères : au moins 30 % pour les échéances et les directs, 10 % pour l'engagement.",
  "envois.parPriorite": "Par priorité",
  "envois.parType": "Par type",
  "envois.cle": "Rappel",
  "envois.total": "Décisions",
  "envois.envoyes": "Envoyés",
  "envois.differes": "Différés",
  "envois.bloques": "Bloqués",
  "envois.echecs": "Échecs",
  "envois.ouverts": "Ouverts sous 24 h",
  "effet.titre": "Effet du rappel d'entraînement",
  "effet.lecture":
    "Part des jours suivis d'une action d'apprentissage dans les 24 h : jours avec rappel, comparés aux jours tirés au sort sans rappel (un sur cinq pendant 4 semaines). On garde le rappel s'il apporte au moins 5 points.",
  "effet.avec": "Avec rappel",
  "effet.sans": "Sans rappel (tirés au sort)",
  "effet.ecart": "{n} points d'écart",
  "relances.titre": "Relances des décrocheurs",
  "relances.lecture": "Relances envoyées sur la période ; revenus : une activité dans les 48 h. « À appeler » : deux relances sans effet.",
  "relances.envoyees": "{n} relances envoyées",
  "relances.revenus": "revenus sous 48 h",
  "relances.aAppeler": "{n} étudiant(s) à appeler",
  "relances.lien": "Voir « À contacter »",

  // ── 6. Copies, séances mal datées, questions ratées ──
  "copies.titre": "Copies en attente de correction, par formateur",
  "copies.lecture":
    "Copies rendues par les étudiants du groupe et pas encore notées. Délai médian : entre la remise et la note, pour les copies corrigées sur la période (cible : moins de 72 h).",
  "copies.formateur": "Formateur",
  "copies.enAttente": "En attente",
  "copies.plusAncienne": "Plus ancienne",
  "copies.auDela72h": "Plus de 72 h",
  "copies.delai": "Délai médian",
  "copies.joursAge": "{n} j",
  "copies.heures": "{n} h",
  "copies.aucune": "Aucune copie en attente : bravo aux formateurs.",
  "anomalies.titre": "À vérifier",
  "malDatees.titre": "Séances démarrées à une autre date que prévue",
  "malDatees.lecture":
    "Comptées partout à leur date réelle (présences, « à contacter », ce tableau). Redatez-les dans le planning si la date prévue est fausse.",
  "malDatees.ligne": "prévue le {prevue}, tenue le {tenue}",
  "malDatees.aucune": "Aucune séance mal datée sur la période.",
  "ratees.titre": "Questions les plus ratées",
  "ratees.lecture":
    "Questions des interrogations liées aux séances (et cartes de révision dès qu'elles seront en ligne), au moins 5 réponses et plus d'une sur trois fausse. Au-delà de 70 % d'erreurs, la question est peut-être mal posée : faites-la relire.",
  "ratees.erreurs": "{n} % d'erreurs sur {sur} réponses",
  "ratees.revision": "carte de révision",
  "ratees.aucune": "Aucune question ratée par plus d'un étudiant sur trois.",

  // ── Tableau de pilotage (/pilotage) ──
  "tableau.lienEngagement": "Engagement et participation",
  "tableau.lienEngagement.texte": "Jour par jour, téléphone, directs, rappels",
  "tableau.actifsAujourdhui": "Actifs aujourd'hui",
  "tableau.actifsAujourdhui.detail": "{n} ont fait une action d'apprentissage",
  "tableau.revenus": "Revenus après le 1er jour",
  "tableau.revenus.detail": "vus au moins deux jours différents",
  "tableau.ontSuivi": "Ont suivi un direct",
  "tableau.ontSuivi.detail": "émargés, ou 30 min en ligne, en 30 jours",
  "tableau.presence": "Présence aux directs",
  "tableau.presence.detail": "là où elle est connue · {n} % inconnue",
  "tableau.presence.detailConnue": "là où elle est connue",
  "tableau.copies": "Copies rendues à ce jour",
  "tableau.copies.detail": "{n} sur {sur}, devoirs ouverts compris",
  "tableau.emargement": "Salles émargées : {e} séances sur {n}",
  "tableau.copiesCourt": "Copies à ce jour",
  "tableau.actifsCourt": "actifs aujourd'hui",

  // ── Export CSV ──
  "csv.campus": "Campus",
  "csv.classe": "Classe",
  "csv.inscrits": "Inscrits",
  "csv.ouverts7j": "Ont ouvert le campus (7 j)",
  "csv.apprenants7j": "Ont fait une action d'apprentissage (7 j)",
  "csv.mediane": "Jours d'apprentissage (médiane, semaine dernière)",
  "csv.presents": "Présents aux directs ({n} j)",
  "csv.absents": "Absents",
  "csv.inconnus": "Présence inconnue",
  "csv.presenceConnue": "Présence connue (%)",
  "csv.copies": "Copies rendues à ce jour (%)",
  "csv.qcmAuto": "QCM automatiques terminés (%)",
});

export type CleEngagement = Parameters<typeof t>[0];
