// Textes du chantier C7 (côté formateur) : « Après la séance », correction
// rapide, relecture facultative des devoirs de l'IA, travail de groupe, rappel
// du matin ; et de la correction automatique (chantier K1, 8 octobre 2026) :
// corrigés du jour, lien de validation de l'e-mail, rappels. Formateurs
// vouvoyés ; étudiants tutoyés (travail de groupe, consignes des devoirs).
// Couche commune : shared/textes/index.ts. Un texte « .un » / « .n » se choisit
// selon le nombre avec selonNombre().
import { creerTextes, type Dictionnaire, type OptionsTexte, type Traducteur } from "./index";

const FR = {
  // ── Après la séance (accueil du formateur) ─────────────────────────────────
  "apres.etiquette": "Après votre séance · {code}",
  "apres.sousTitre": "Le campus s'est occupé de la suite.",
  "apres.coursComplet.prete": "Cours résumé prêt",
  "apres.coursComplet.en_cours": "Cours résumé en préparation",
  "apres.coursComplet.a_venir": "Cours résumé préparé cette nuit",
  "apres.coursComplet.erreur": "Cours résumé : nouvel essai automatique",
  "apres.coursComplet.ouvert.un": "ouvert par 1 étudiant",
  "apres.coursComplet.ouvert.n": "ouvert par {n} étudiants",
  "apres.coursComplet.attente": "quiz, exercices et fiches pour vos étudiants",
  "apres.ouvrir": "Ouvrir",
  "apres.quiz.titre.un": "QCM envoyé à 1 étudiant",
  "apres.quiz.titre.n": "QCM envoyé à {n} étudiants",
  "apres.depot.titre.un": "Exercice envoyé à 1 étudiant",
  "apres.depot.titre.n": "Exercice envoyé à {n} étudiants",
  "apres.quiz.faits.zero": "personne ne l'a encore fait",
  "apres.quiz.faits.un": "1 l'a fait",
  "apres.quiz.faits.n": "{n} l'ont fait",
  "apres.quiz.moyenne": "moyenne {note}/{bareme}",
  "apres.depot.rendus.zero": "aucune copie pour l'instant",
  "apres.depot.rendus.un": "1 copie rendue",
  "apres.depot.rendus.n": "{n} copies rendues",
  // Exercice de la routine du soir sans corrigé : le corriger est facultatif (décision D2), jamais « à corriger ».
  "apres.depot.facultatif": "correction facultative",
  // Exercice corrigé par le campus (D6, 8 octobre 2026).
  "apres.depot.campus.notees.zero": "aucune notée pour l'instant",
  "apres.depot.campus.notees.un": "1 notée",
  "apres.depot.campus.notees.n": "{n} notées",
  "apres.depot.campus.attente.un": "1 en attente de correction",
  "apres.depot.campus.attente.n": "{n} en attente de correction",
  "apres.depot.campus.revoir.un": "1 à revoir par vous",
  "apres.depot.campus.revoir.n": "{n} à revoir par vous",
  "apres.devoir.proposeLe": "mis en avant {quand}",
  "apres.devoir.aRevoir": "plus mis en avant (à revoir)",
  "apres.devoir.masque": "masqué aux étudiants",
  "apres.replay.pret": "Replay en ligne",
  "apres.replay.ouvert.zero": "pas encore ouvert",
  "apres.replay.ouvert.un": "ouvert par 1 étudiant",
  "apres.replay.ouvert.n": "ouvert par {n} étudiants",
  "apres.revision": "Révision : {etudiants} étudiants, {reponses} réponses",
  "apres.plusRatee": "La plus ratée : « {texte} » ({taux} % d'erreurs)",
  "apres.signalees.un": "1 carte signalée par les étudiants",
  "apres.signalees.n": "{n} cartes signalées par les étudiants",
  "apres.presents": "présents",
  "apres.inconnus.un": "1 inconnu (salle non émargée)",
  "apres.inconnus.n": "{n} inconnus (salle non émargée)",
  "apres.questions.un": "question posée",
  "apres.questions.n": "questions posées",
  "apres.sondages.un": "sondage",
  "apres.sondages.n": "sondages",
  "apres.astuceSondage": "Un sondage pendant le direct fait participer les salles : les étudiants répondent depuis leur téléphone.",
  "apres.bilan": "Bilan de la séance",
  "apres.corriger.un": "Corriger 1 copie",
  "apres.corriger.n": "Corriger {n} copies",
  "apres.corriger.ancienne": "La plus ancienne attend depuis {duree}.",
  "apres.corriger.pourquoi": "Une copie notée vite donne envie de rendre la suivante.",
  "apres.aPublier.un": "1 note posée attend d'être envoyée.",
  "apres.aPublier.n": "{n} notes posées attendent d'être envoyées.",
  "apres.relire.un": "Relire le devoir écrit par l'IA (facultatif)",
  "apres.relire.n": "Relire les {n} devoirs écrits par l'IA (facultatif)",
  "apres.facultatives.un": "1 copie d'un exercice du campus (correction facultative)",
  "apres.facultatives.n": "{n} copies des exercices du campus (correction facultative)",
  "apres.sansSeance.titre": "Copies à corriger",

  // ── Correction rapide (/corriger) ──────────────────────────────────────────
  "corriger.etiquette": "Correction rapide",
  "corriger.titre": "Copies à corriger",
  "corriger.resume.un": "1 copie attend sa note.",
  "corriger.resume.n": "{n} copies attendent leur note.",
  "corriger.ancienne": "La plus ancienne depuis {duree}.",
  "corriger.commencer": "Corriger la plus ancienne",
  "corriger.reprendre": "Continuer",
  "corriger.parDevoir": "Par devoir",
  "corriger.devoir.un": "1 copie",
  "corriger.devoir.n": "{n} copies",
  "corriger.depuis": "depuis {duree}",
  "corriger.aPublier.un": "1 note posée n'est pas encore envoyée.",
  "corriger.aPublier.n": "{n} notes posées ne sont pas encore envoyées.",
  "corriger.envoyerPosees": "Les envoyer",
  "corriger.posees.envoyees.un": "1 note envoyée. L'étudiant est prévenu.",
  "corriger.posees.envoyees.n": "{n} notes envoyées. Les étudiants sont prévenus.",
  "corriger.vide.titre": "Aucune copie en attente",
  "corriger.vide.texte": "Les copies de vos devoirs arrivent ici, la plus ancienne en premier.",
  "corriger.facultatives.titre": "Exercices du campus · facultatif",
  "corriger.facultatives.texte":
    "Le campus a envoyé ces exercices à vos étudiants sans vous. Les corriger est facultatif : vous ne recevrez aucun rappel pour ces copies.",
  "corriger.bravo": "Bravo : toutes les copies ont leur note.",
  "corriger.aujourdhui.un": "1 note envoyée aujourd'hui.",
  "corriger.aujourdhui.n": "{n} notes envoyées aujourd'hui.",
  "corriger.toutesLesCopies": "Toutes les corrections",
  "corriger.position": "Copie {i} sur {n}",
  "corriger.quitter": "Quitter",
  "corriger.rendue": "Rendue il y a {quand}",
  "corriger.enRetard": "en retard",
  "corriger.note": "Note sur {bareme}",
  "corriger.autre": "Autre",
  "corriger.autreNote": "Note exacte",
  "corriger.ia.propose": "Proposé par l'IA : {note}/{bareme}",
  "corriger.ia.reprendre": "Reprendre",
  "corriger.ia.demander": "Proposer une note (IA)",
  "corriger.ia.relire": "Proposition de l'IA : relisez-la avant d'envoyer.",
  "corriger.ia.prete": "Correction proposée par l'IA. Relisez-la avant d'envoyer.",
  "corriger.commentaire": "Un mot pour l'étudiant",
  "corriger.commentaire.aide": "Facultatif. Touchez une phrase pour l'ajouter.",
  "corriger.vocal": "Ou un message vocal",
  "corriger.envoyer": "Envoyer {note}/{bareme} à {prenom}",
  "corriger.choisir": "Choisissez une note",
  "corriger.passer": "Plus tard",
  "corriger.detaillee": "Correction détaillée avec la grille",
  "corriger.envoyee": "Note envoyée à {prenom}.",
  "corriger.horsLimites": "La note doit être entre 0 et {bareme}.",
  "corriger.dejaCorrigee": "Cette copie a déjà sa note.",
  "corriger.vers.copies": "Voir les copies du devoir",
  // Phrases rapides : elles s'adressent à l'étudiant, donc tutoyées.
  "corriger.phrase.1": "Bon travail, continue comme ça !",
  "corriger.phrase.2": "Notions bien comprises.",
  "corriger.phrase.3": "Explique davantage ta démarche.",
  "corriger.phrase.4": "Relis la consigne : une partie manque.",
  "corriger.phrase.5": "Soigne la présentation.",
  "corriger.phrase.6": "Revois le cours résumé sur ce point.",

  // ── Relecture facultative des devoirs écrits par l'IA ──────────────────────
  "relire.etiquette": "Facultatif",
  "relire.titre": "Devoirs écrits par l'IA",
  "relire.intro":
    "Le campus prépare un QCM et un exercice après chaque séance enregistrée et les envoie à vos étudiants. Chaque jour, il vous envoie leurs corrigés : validez-les ou corrigez-les. Sans réponse, ils sont tenus pour bons au bout de 24 heures et le campus s'en sert pour noter les copies.",
  "relire.vide": "Rien à relire : les derniers devoirs du campus sont déjà regardés.",
  "relire.quiz": "QCM",
  "relire.depot": "Exercice",
  "relire.propose": "Mis en avant auprès des étudiants",
  "relire.proposeLe": "Mis en avant {quand}",
  "relire.aRevoir": "Plus mis en avant : il reste dans « Devoirs »",
  "relire.masque": "Masqué aux étudiants",
  "relire.voirQuestions.un": "Voir la question",
  "relire.voirQuestions.n": "Voir les {n} questions",
  "relire.masquerQuestions": "Masquer les questions",
  "relire.bonneReponse": "Bonne réponse",
  "relire.ok": "C'est bon",
  "relire.modifier": "Modifier",
  "relire.nePasProposer": "Ne pas le mettre en avant",
  "relire.annuler": "Annuler mon choix",
  "relire.fait.valide": "Merci : le devoir est validé.",
  "relire.fait.a_revoir": "Le campus ne le met plus en avant. Modifiez-le quand vous voulez.",
  "relire.fait.annule": "Choix annulé : la règle habituelle s'applique.",
  "relire.retour": "Aujourd'hui",

  // ── Travail de groupe du cours complet ─────────────────────────────────────
  "groupe.ouvrir": "Ouvrir le travail de groupe en devoir",
  "groupe.ouvrir.aide": "Un brouillon prêt à relire : sujet, rôles, livrable et date limite. Rien ne part avant votre publication.",
  "groupe.brouillon": "Brouillon prêt : relisez-le puis publiez-le.",
  "groupe.relire": "Relire et publier",
  "groupe.publie.zero": "Devoir ouvert · aucune copie pour l'instant",
  "groupe.publie.un": "Devoir ouvert · 1 copie rendue",
  "groupe.publie.n": "Devoir ouvert · {n} copies rendues",
  "groupe.voirCopies": "Voir les copies",
  "groupe.cree": "Brouillon créé. Relisez-le, puis cochez « Publié ».",
  "groupe.rendre": { tu: "Rendre le travail de ton groupe", vous: "Rendre le travail du groupe" },
  "groupe.rendre.aide": {
    tu: "Photo, fichier ou texte, avant le {date}. Un seul membre peut rendre pour tout le groupe en citant les noms.",
    vous: "Photo, fichier ou texte, avant le {date}.",
  },
  "groupe.rendu": { tu: "Travail rendu · reçu {recu}", vous: "Travail rendu · reçu {recu}" },
  "groupe.voirRendu": { tu: "Voir ma copie", vous: "Voir la copie" },
  // Devoir créé à partir du travail de groupe : il est lu par les étudiants (tutoiement).
  "groupe.devoir.titre": "Travail de groupe : {sujet}",
  "groupe.devoir.roles": "**Les rôles dans le groupe :**",
  "groupe.devoir.livrable": "**À rendre :** {livrable}",
  "groupe.devoir.comment":
    "**Comment rendre :** forme ton groupe, répartissez-vous les rôles, puis rends le travail ici : photos nettes, fichier (PDF, Word, PowerPoint…) ou texte. Un seul membre peut rendre pour tout le groupe : si c'est toi, écris en tête les noms et matricules de chacun. Tu peux aussi rendre ta propre partie. Le campus corrige le travail d'après le corrigé validé par ton formateur, avec des conseils critère par critère.",
  "groupe.devoir.origine": "_Travail de groupe du cours résumé de la séance du {jour}._",
  "groupe.critere.contenu": "Contenu juste et appuyé sur le cours",
  "groupe.critere.roles": "Chaque rôle tenu",
  "groupe.critere.livrable": "Livrable complet",
  "groupe.critere.presentation": "Présentation claire",

  // ── Durées (« depuis 3 jours ») ────────────────────────────────────────────
  "duree.moinsHeure": "moins d'une heure",
  "duree.heure.un": "1 heure",
  "duree.heure.n": "{n} heures",
  "duree.jour.un": "1 jour",
  "duree.jour.n": "{n} jours",

  // ── Rappel du matin des formateurs (cloche et téléphone, vouvoiement) ──────
  "rappel.copies.titre.un": "Une copie attend votre correction",
  "rappel.copies.titre.n": "{n} copies attendent votre correction",
  "rappel.copies.corps": "La plus ancienne depuis {jours} jours. Quelques minutes sur votre téléphone suffisent.",
  "rappel.salon.titre.un": "Une question du salon attend votre réponse",
  "rappel.salon.titre.n": "{n} questions du salon attendent votre réponse",
  "rappel.salon.corps": "Vos étudiants l'ont posée dans « Questions du cours » il y a plus d'un jour.",
  "rappel.salon.enPlus.un": "Et une question du salon attend votre réponse.",
  "rappel.salon.enPlus.n": "Et {n} questions du salon attendent votre réponse.",
  // Correction automatique : copies que le campus vous laisse, relectures demandées, corrigés à valider.
  "rappel.relectures.titre.un": "Un étudiant demande la relecture de sa note",
  "rappel.relectures.titre.n": "{n} étudiants demandent la relecture de leur note",
  "rappel.relectures.corps": "Gardez la note ou changez-la, avec un mot pour l'étudiant.",
  "rappel.relectures.enPlus.un": "Et un étudiant demande la relecture de sa note.",
  "rappel.relectures.enPlus.n": "Et {n} étudiants demandent la relecture de leur note.",
  "rappel.revoir.titre.un": "Une copie attend votre décision",
  "rappel.revoir.titre.n": "{n} copies attendent votre décision",
  "rappel.revoir.corps": "Le campus ne les a pas notées seul (consigne cachée, page illisible, vidéo…) : à vous de voir.",
  "rappel.revoir.enPlus.un": "Et une copie attend votre décision.",
  "rappel.revoir.enPlus.n": "Et {n} copies attendent votre décision.",
  "rappel.copies.enPlus.un": "Et une copie attend votre correction.",
  "rappel.copies.enPlus.n": "Et {n} copies attendent votre correction.",
  "rappel.corriges.enPlus.un": "Et un corrigé attend votre validation.",
  "rappel.corriges.enPlus.n": "Et {n} corrigés attendent votre validation.",

  // ── Corrigés du jour (correction automatique, 8 octobre 2026) ──────────────
  // Notification et rappel (cloche et téléphone).
  "corriges.notif.titre.un": "Corrigé du jour : 1 devoir à vérifier",
  "corriges.notif.titre.n": "Corrigés du jour : {n} devoirs à vérifier",
  "corriges.notif.corps.un": "{liste}. Est-ce conforme à ce que vous avez expliqué ? Sans réponse, il sera tenu pour bon {quand}.",
  "corriges.notif.corps.n": "{liste}. Est-ce conforme à ce que vous avez expliqué ? Sans réponse, ils seront tenus pour bons {quand}.",
  "corriges.rappel.titre.un": "Un corrigé sera tenu pour bon à {heure}",
  "corriges.rappel.titre.n": "{n} corrigés seront tenus pour bons à {heure}",
  "corriges.rappel.corps": "Sans réponse de votre part, le campus s'en servira pour noter les copies. Un coup d'œil suffit.",
  // E-mail du jour.
  "corriges.email.sujet.un": "Corrigé du jour : 1 devoir à vérifier",
  "corriges.email.sujet.n": "Corrigés du jour : {n} devoirs à vérifier",
  "corriges.email.etiquette": "Corrigés du jour · {date}",
  "corriges.email.titre": "Bonjour {appel},",
  "corriges.email.apercu": "Est-ce conforme à ce que vous avez expliqué ? Un toucher suffit pour valider.",
  "corriges.email.intro.un": "Voici le corrigé du devoir que vos étudiants ont reçu. Est-ce qu'il correspond à ce que vous avez expliqué ?",
  "corriges.email.intro.n": "Voici les corrigés des {n} devoirs que vos étudiants ont reçus. Est-ce qu'ils correspondent à ce que vous avez expliqué ?",
  "corriges.email.regle.un":
    "Le campus s'en sert comme barème pour corriger les copies et publier les notes. **Sans réponse de votre part, il sera tenu pour bon {quand}.** Vous pourrez encore le modifier ensuite : les copies seront alors corrigées de nouveau.",
  "corriges.email.regle.n":
    "Le campus s'en sert comme barème pour corriger les copies et publier les notes. **Sans réponse de votre part, ils seront tenus pour bons {quand}.** Vous pourrez encore les modifier ensuite : les copies seront alors corrigées de nouveau.",
  "corriges.email.valider": "Tout est juste : valider",
  "corriges.email.voir": "Voir et modifier",
  "corriges.email.apres.confirmer": "« Tout est juste » ouvre une page de confirmation : rien n'est validé avant votre confirmation.",
  "corriges.email.apres.qcm": "Une bonne réponse est fausse ? Corrigez-la sur le campus : les notes du QCM sont recalculées.",
  "corriges.email.autres.un": "Et 1 autre devoir à vérifier sur le campus.",
  "corriges.email.autres.n": "Et {n} autres devoirs à vérifier sur le campus.",
  "corriges.email.bloc.quiz": "QCM · {code}",
  "corriges.email.bloc.depot": "Exercice · {code}",
  "corriges.email.bloc.questions.un": "1 question",
  "corriges.email.bloc.questions.n": "{n} questions",
  "corriges.email.question": "**{i}. {enonce}**\nBonne réponse : **{reponse}**",
  "corriges.email.explication": "\n{explication}",
  "corriges.email.consigne": "**Consigne donnée aux étudiants :**\n{texte}",
  "corriges.email.grille": "**Grille ({bareme} points) :** {criteres}",
  "corriges.email.sansGrille": "**Barème :** note globale sur {bareme}",
  "corriges.email.corrige": "**Corrigé :**\n{texte}",
  "corriges.email.suite": "Lire le corrigé en entier sur le campus",
  "corriges.email.lireTout": "Voir sur le campus",
  "corriges.email.vrai": "Vrai",
  "corriges.email.faux": "Faux",
  // Page du lien de validation (sans connexion).
  "corriges.lien.etiquette": "Corrigés du jour",
  "corriges.lien.titre.un": "Valider ce corrigé ?",
  "corriges.lien.titre.n": "Valider ces corrigés ?",
  "corriges.lien.intro": "Le campus s'en servira comme barème pour corriger les copies et publier les notes. Vous pourrez encore le modifier ensuite sur le campus.",
  "corriges.lien.valider.un": "Valider ce corrigé",
  "corriges.lien.valider.n": "Valider ces {n} corrigés",
  "corriges.lien.voir": "Voir et modifier sur le campus",
  "corriges.lien.etat.propose": "À valider · tenu pour bon {quand}",
  "corriges.lien.etat.proposeSansDate": "À valider",
  "corriges.lien.etat.valide": "Déjà validé",
  "corriges.lien.etat.tacite": "Déjà tenu pour bon",
  "corriges.lien.etat.modifie": "Modifié depuis l'e-mail : ouvrez-le sur le campus",
  "corriges.lien.etat.introuvable": "Ce devoir n'existe plus",
  "corriges.lien.rien.titre": "Rien à valider",
  "corriges.lien.rien": "Ces corrigés sont déjà validés, tenus pour bons, ou ont été modifiés depuis l'e-mail.",
  "corriges.lien.fait.titre": "C'est fait, merci !",
  "corriges.lien.fait.un": "Le corrigé est validé.",
  "corriges.lien.fait.n": "{n} corrigés sont validés.",
  "corriges.lien.fait.suite": "Le campus corrige les copies d'après ce barème et publie les notes. Vous pouvez encore le modifier sur le campus.",
  "corriges.lien.expire.titre": "Ce lien a expiré",
  "corriges.lien.expire": "Il reste valable 7 jours. Ouvrez vos corrigés sur le campus pour les valider ou les modifier.",
  "corriges.lien.invalide.titre": "Lien incomplet",
  "corriges.lien.invalide": "Ce lien n'est pas valide (il a peut-être été coupé par la messagerie). Ouvrez vos corrigés sur le campus.",
  "corriges.lien.refuse": "Ce lien ne vous permet plus de valider ces corrigés. Ouvrez-les sur le campus.",
  "corriges.lien.ouvrir": "Ouvrir le campus",
  // Erreurs des routes du formateur.
  "corriges.erreur.version": "Ce corrigé a changé entre-temps (version {version}). Rechargez la page pour voir la dernière version.",
  "corriges.erreur.enPreparation": "Le campus n'a pas encore rédigé ce corrigé. Vous pouvez l'écrire vous-même : « Modifier ».",
  "corriges.erreur.quiz": "Les bonnes réponses d'un QCM se corrigent dans l'éditeur de questions : les notes sont alors recalculées.",
  "corriges.erreur.vide": "Le corrigé est vide.",
  "corriges.erreur.long": "Le corrigé est trop long ({max} caractères au plus).",
  "corriges.erreur.droit": "Seuls le formateur du cours et la direction peuvent valider ce corrigé.",
  "corriges.erreur.lecture": "Seuls le formateur du cours et la direction peuvent ouvrir ce corrigé.",
  "corriges.erreur.aucun": "Ce devoir n'a pas de corrigé.",
} satisfies Dictionnaire;

export const t = creerTextes(FR);
export type CleEnseigner = keyof typeof FR;

/**
 * Texte au singulier ou au pluriel : « base.un » pour 1, « base.n » au-delà
 * (et « base.zero » pour 0 quand la clé existe). {n} reçoit le nombre.
 */
export function selonNombre(tx: Traducteur<CleEnseigner>, base: string, n: number, options: OptionsTexte = {}): string {
  const v = { n, ...options.v };
  const suffixe = n === 0 && `${base}.zero` in FR ? "zero" : n === 1 ? "un" : "n";
  return tx(`${base}.${suffixe}` as CleEnseigner, { ...options, v });
}
