// Textes du chantier C7 (côté formateur) : « Après la séance », correction
// rapide, relecture facultative des devoirs de l'IA, travail de groupe, rappel
// du matin. Formateurs vouvoyés ; étudiants tutoyés (travail de groupe).
// Couche commune : shared/textes/index.ts. Un texte « .un » / « .n » se choisit
// selon le nombre avec selonNombre().
import { creerTextes, type Dictionnaire, type OptionsTexte, type Traducteur } from "./index";

const FR = {
  // ── Après la séance (accueil du formateur) ─────────────────────────────────
  "apres.etiquette": "Après votre séance · {code}",
  "apres.sousTitre": "Le campus s'est occupé de la suite.",
  "apres.coursComplet.prete": "Cours complet prêt",
  "apres.coursComplet.en_cours": "Cours complet en préparation",
  "apres.coursComplet.a_venir": "Cours complet préparé cette nuit",
  "apres.coursComplet.erreur": "Cours complet : nouvel essai automatique",
  "apres.coursComplet.ouvert.un": "ouvert par 1 étudiant",
  "apres.coursComplet.ouvert.n": "ouvert par {n} étudiants",
  "apres.coursComplet.attente": "quiz, exercices et fiches pour vos étudiants",
  "apres.ouvrir": "Ouvrir",
  "apres.quiz.titre.un": "QCM envoyé à 1 étudiant",
  "apres.quiz.titre.n": "QCM envoyé à {n} étudiants",
  "apres.depot.titre.un": "Exercice envoyé à 1 étudiant",
  "apres.depot.titre.n": "Exercice envoyé à {n} étudiants",
  "apres.quiz.faits.zero": "personne ne l'a encore fait",
  "apres.quiz.faits.un": "1 l'a fait",
  "apres.quiz.faits.n": "{n} l'ont fait",
  "apres.quiz.moyenne": "moyenne {note}/{bareme}",
  "apres.depot.rendus.zero": "aucune copie pour l'instant",
  "apres.depot.rendus.un": "1 copie rendue",
  "apres.depot.rendus.n": "{n} copies rendues",
  // Exercice de la routine du soir : le corriger est facultatif (décision D2), jamais « à corriger ».
  "apres.depot.facultatif": "correction facultative",
  "apres.devoir.proposeLe": "mis en avant {quand}",
  "apres.devoir.aRevoir": "plus mis en avant (à revoir)",
  "apres.devoir.masque": "masqué aux étudiants",
  "apres.replay.pret": "Replay en ligne",
  "apres.replay.ouvert.zero": "pas encore ouvert",
  "apres.replay.ouvert.un": "ouvert par 1 étudiant",
  "apres.replay.ouvert.n": "ouvert par {n} étudiants",
  "apres.revision": "Révision : {etudiants} étudiants, {reponses} réponses",
  "apres.plusRatee": "La plus ratée : « {texte} » ({taux} % d'erreurs)",
  "apres.signalees.un": "1 carte signalée par les étudiants",
  "apres.signalees.n": "{n} cartes signalées par les étudiants",
  "apres.presents": "présents",
  "apres.inconnus.un": "1 inconnu (salle non émargée)",
  "apres.inconnus.n": "{n} inconnus (salle non émargée)",
  "apres.questions.un": "question posée",
  "apres.questions.n": "questions posées",
  "apres.sondages.un": "sondage",
  "apres.sondages.n": "sondages",
  "apres.astuceSondage": "Un sondage pendant le direct fait participer les salles : les étudiants répondent depuis leur téléphone.",
  "apres.bilan": "Bilan de la séance",
  "apres.corriger.un": "Corriger 1 copie",
  "apres.corriger.n": "Corriger {n} copies",
  "apres.corriger.ancienne": "La plus ancienne attend depuis {duree}.",
  "apres.corriger.pourquoi": "Une copie notée vite donne envie de rendre la suivante.",
  "apres.aPublier.un": "1 note posée attend d'être envoyée.",
  "apres.aPublier.n": "{n} notes posées attendent d'être envoyées.",
  "apres.relire.un": "Relire le devoir écrit par l'IA (facultatif)",
  "apres.relire.n": "Relire les {n} devoirs écrits par l'IA (facultatif)",
  "apres.facultatives.un": "1 copie d'un exercice du campus (correction facultative)",
  "apres.facultatives.n": "{n} copies des exercices du campus (correction facultative)",
  "apres.sansSeance.titre": "Copies à corriger",

  // ── Correction rapide (/corriger) ──────────────────────────────────────────
  "corriger.etiquette": "Correction rapide",
  "corriger.titre": "Copies à corriger",
  "corriger.resume.un": "1 copie attend sa note.",
  "corriger.resume.n": "{n} copies attendent leur note.",
  "corriger.ancienne": "La plus ancienne depuis {duree}.",
  "corriger.commencer": "Corriger la plus ancienne",
  "corriger.reprendre": "Continuer",
  "corriger.parDevoir": "Par devoir",
  "corriger.devoir.un": "1 copie",
  "corriger.devoir.n": "{n} copies",
  "corriger.depuis": "depuis {duree}",
  "corriger.aPublier.un": "1 note posée n'est pas encore envoyée.",
  "corriger.aPublier.n": "{n} notes posées ne sont pas encore envoyées.",
  "corriger.envoyerPosees": "Les envoyer",
  "corriger.posees.envoyees.un": "1 note envoyée. L'étudiant est prévenu.",
  "corriger.posees.envoyees.n": "{n} notes envoyées. Les étudiants sont prévenus.",
  "corriger.vide.titre": "Aucune copie en attente",
  "corriger.vide.texte": "Les copies de vos devoirs arrivent ici, la plus ancienne en premier.",
  "corriger.facultatives.titre": "Exercices du campus · facultatif",
  "corriger.facultatives.texte":
    "Le campus a envoyé ces exercices à vos étudiants sans vous. Les corriger est facultatif : vous ne recevrez aucun rappel pour ces copies.",
  "corriger.bravo": "Bravo : toutes les copies ont leur note.",
  "corriger.aujourdhui.un": "1 note envoyée aujourd'hui.",
  "corriger.aujourdhui.n": "{n} notes envoyées aujourd'hui.",
  "corriger.toutesLesCopies": "Toutes les corrections",
  "corriger.position": "Copie {i} sur {n}",
  "corriger.quitter": "Quitter",
  "corriger.rendue": "Rendue il y a {quand}",
  "corriger.enRetard": "en retard",
  "corriger.note": "Note sur {bareme}",
  "corriger.autre": "Autre",
  "corriger.autreNote": "Note exacte",
  "corriger.ia.propose": "Proposé par l'IA : {note}/{bareme}",
  "corriger.ia.reprendre": "Reprendre",
  "corriger.ia.demander": "Proposer une note (IA)",
  "corriger.ia.relire": "Une proposition, jamais une note : relisez avant d'envoyer.",
  "corriger.ia.prete": "Correction proposée par l'IA. Relisez-la avant d'envoyer.",
  "corriger.commentaire": "Un mot pour l'étudiant",
  "corriger.commentaire.aide": "Facultatif. Touchez une phrase pour l'ajouter.",
  "corriger.vocal": "Ou un message vocal",
  "corriger.envoyer": "Envoyer {note}/{bareme} à {prenom}",
  "corriger.choisir": "Choisissez une note",
  "corriger.passer": "Plus tard",
  "corriger.detaillee": "Correction détaillée avec la grille",
  "corriger.envoyee": "Note envoyée à {prenom}.",
  "corriger.horsLimites": "La note doit être entre 0 et {bareme}.",
  "corriger.dejaCorrigee": "Cette copie a déjà sa note.",
  "corriger.vers.copies": "Voir les copies du devoir",
  // Phrases rapides : elles s'adressent à l'étudiant, donc tutoyées.
  "corriger.phrase.1": "Bon travail, continue comme ça !",
  "corriger.phrase.2": "Notions bien comprises.",
  "corriger.phrase.3": "Explique davantage ta démarche.",
  "corriger.phrase.4": "Relis la consigne : une partie manque.",
  "corriger.phrase.5": "Soigne la présentation.",
  "corriger.phrase.6": "Revois le cours complet sur ce point.",

  // ── Relecture facultative des devoirs écrits par l'IA ──────────────────────
  "relire.etiquette": "Facultatif",
  "relire.titre": "Devoirs écrits par l'IA",
  "relire.intro":
    "Le campus prépare un QCM et un exercice après chaque séance enregistrée et les envoie à vos étudiants sans rien vous demander. Vous pouvez les relire ici si vous le souhaitez. Corriger les copies de l'exercice est aussi facultatif : aucun rappel ne vous est envoyé pour elles.",
  "relire.vide": "Rien à relire : les derniers devoirs du campus sont déjà regardés.",
  "relire.quiz": "QCM",
  "relire.depot": "Exercice",
  "relire.propose": "Mis en avant auprès des étudiants",
  "relire.proposeLe": "Mis en avant {quand}",
  "relire.aRevoir": "Plus mis en avant : il reste dans « Devoirs »",
  "relire.masque": "Masqué aux étudiants",
  "relire.voirQuestions.un": "Voir la question",
  "relire.voirQuestions.n": "Voir les {n} questions",
  "relire.masquerQuestions": "Masquer les questions",
  "relire.bonneReponse": "Bonne réponse",
  "relire.ok": "C'est bon",
  "relire.modifier": "Modifier",
  "relire.nePasProposer": "Ne pas le mettre en avant",
  "relire.annuler": "Annuler mon choix",
  "relire.fait.valide": "Merci : le devoir est validé.",
  "relire.fait.a_revoir": "Le campus ne le met plus en avant. Modifiez-le quand vous voulez.",
  "relire.fait.annule": "Choix annulé : la règle habituelle s'applique.",
  "relire.retour": "Aujourd'hui",

  // ── Travail de groupe du cours complet ─────────────────────────────────────
  "groupe.ouvrir": "Ouvrir le travail de groupe en devoir",
  "groupe.ouvrir.aide": "Un brouillon prêt à relire : sujet, rôles, livrable et date limite. Rien ne part avant votre publication.",
  "groupe.brouillon": "Brouillon prêt : relisez-le puis publiez-le.",
  "groupe.relire": "Relire et publier",
  "groupe.publie.zero": "Devoir ouvert · aucune copie pour l'instant",
  "groupe.publie.un": "Devoir ouvert · 1 copie rendue",
  "groupe.publie.n": "Devoir ouvert · {n} copies rendues",
  "groupe.voirCopies": "Voir les copies",
  "groupe.cree": "Brouillon créé. Relisez-le, puis cochez « Publié ».",
  "groupe.rendre": { tu: "Rendre le travail de ton groupe", vous: "Rendre le travail du groupe" },
  "groupe.rendre.aide": {
    tu: "Photo, fichier ou texte, avant le {date}. Un seul membre peut rendre pour tout le groupe en citant les noms.",
    vous: "Photo, fichier ou texte, avant le {date}.",
  },
  "groupe.rendu": { tu: "Travail rendu · reçu {recu}", vous: "Travail rendu · reçu {recu}" },
  "groupe.voirRendu": { tu: "Voir ma copie", vous: "Voir la copie" },
  // Devoir créé à partir du travail de groupe : il est lu par les étudiants (tutoiement).
  "groupe.devoir.titre": "Travail de groupe : {sujet}",
  "groupe.devoir.roles": "**Les rôles dans le groupe :**",
  "groupe.devoir.livrable": "**À rendre :** {livrable}",
  "groupe.devoir.comment":
    "**Comment rendre :** formez votre groupe, répartissez les rôles, puis rendez le travail ici : photos, fichier (PDF, Word, PowerPoint…) ou texte. Un seul membre peut rendre pour tout le groupe : écris alors en tête les noms et matricules de chacun. Tu peux aussi rendre ta propre partie.",
  "groupe.devoir.origine": "_Travail de groupe du cours complet de la séance du {jour}._",
  "groupe.critere.contenu": "Contenu juste et appuyé sur le cours",
  "groupe.critere.roles": "Chaque rôle tenu",
  "groupe.critere.livrable": "Livrable complet",
  "groupe.critere.presentation": "Présentation claire",

  // ── Durées (« depuis 3 jours ») ────────────────────────────────────────────
  "duree.moinsHeure": "moins d'une heure",
  "duree.heure.un": "1 heure",
  "duree.heure.n": "{n} heures",
  "duree.jour.un": "1 jour",
  "duree.jour.n": "{n} jours",

  // ── Rappel du matin des formateurs (cloche et téléphone, vouvoiement) ──────
  "rappel.copies.titre.un": "Une copie attend votre correction",
  "rappel.copies.titre.n": "{n} copies attendent votre correction",
  "rappel.copies.corps": "La plus ancienne depuis {jours} jours. Quelques minutes sur votre téléphone suffisent.",
  "rappel.salon.titre.un": "Une question du salon attend votre réponse",
  "rappel.salon.titre.n": "{n} questions du salon attendent votre réponse",
  "rappel.salon.corps": "Vos étudiants l'ont posée dans « Questions du cours » il y a plus d'un jour.",
  "rappel.salon.enPlus.un": "Et une question du salon attend votre réponse.",
  "rappel.salon.enPlus.n": "Et {n} questions du salon attendent votre réponse.",
} satisfies Dictionnaire;

export const t = creerTextes(FR);
export type CleEnseigner = keyof typeof FR;

/**
 * Texte au singulier ou au pluriel : « base.un » pour 1, « base.n » au-delà
 * (et « base.zero » pour 0 quand la clé existe). {n} reçoit le nombre.
 */
export function selonNombre(tx: Traducteur<CleEnseigner>, base: string, n: number, options: OptionsTexte = {}): string {
  const v = { n, ...options.v };
  const suffixe = n === 0 && `${base}.zero` in FR ? "zero" : n === 1 ? "un" : "n";
  return tx(`${base}.${suffixe}` as CleEnseigner, { ...options, v });
}
