// Textes du chantier C5 (progression et Coupe), pour la couche de textes
// commune (shared/textes/index.ts) : étudiants tutoyés, personnel vouvoyé.
// Les badges et « Ma progression » ne parlent qu'aux étudiants (tutoiement) ;
// la Coupe parle à tous ; l'écran de salle s'adresse à la salle (vous).
import { creerTextes } from "./index";

export const t = creerTextes({
  // ── Familles d'actes (« ce qui t'a rapporté des points ») ──
  "famille.direct": "Direct",
  "famille.participation": "Participation au direct",
  "famille.devoir": "Copie rendue",
  "famille.quiz": "Interrogation",
  "famille.lecon": "Leçon terminée",
  "famille.replay": "Replay d'un cours manqué",
  "famille.revision": "Révision",
  "famille.entrainement": "Entraînement du cours complet",
  "famille.objectif": "Objectif du jour",

  // ── Badges ──
  "badge.premier_pas.nom": "Premier pas",
  "badge.premier_pas.desc": "Ton premier acte d'apprentissage sur le campus.",
  "badge.premiere_revision.nom": "Première révision",
  "badge.premiere_revision.desc": "Ta première révision du jour.",
  "badge.defi_classe_5.nom": "Défis de la classe",
  "badge.defi_classe_5.desc": "Relève 5 fois le défi de ta classe.",
  "badge.semaines_4.nom": "Régulier",
  "badge.semaines_4.desc": "4 semaines réussies d'affilée.",
  "badge.semaines_12.nom": "Infatigable",
  "badge.semaines_12.desc": "12 semaines réussies d'affilée.",
  "badge.directs_5.nom": "Assidu",
  "badge.directs_5.desc": "Présent à 5 directs.",
  "badge.directs_10.nom": "Pilier du direct",
  "badge.directs_10.desc": "Présent à 10 directs.",
  "badge.sans_faute.nom": "Sans faute",
  "badge.sans_faute.desc": "Une interrogation avec tous les points.",
  "badge.question_votee.nom": "Bonne question",
  "badge.question_votee.desc": "Une question en direct soutenue par 3 camarades.",
  "badge.devoirs_a_l_heure_5.nom": "Ponctuel",
  "badge.devoirs_a_l_heure_5.desc": "5 copies rendues à l'heure.",
  "badge.objectif_jour_7.nom": "Objectif tenu",
  "badge.objectif_jour_7.desc": "7 objectifs du jour validés.",
  "badge.reste": "Encore {n} {unite} pour {nom}",
  "unite.actes.1": "acte d'apprentissage",
  "unite.actes.n": "actes d'apprentissage",
  "unite.reponsesRevision.1": "révision",
  "unite.reponsesRevision.n": "révisions",
  "unite.defis.1": "défi de la classe",
  "unite.defis.n": "défis de la classe",
  "unite.record.1": "semaine réussie",
  "unite.record.n": "semaines réussies",
  "unite.directs.1": "direct",
  "unite.directs.n": "directs",
  "unite.sansFaute.1": "interrogation sans faute",
  "unite.sansFaute.n": "interrogations sans faute",
  "unite.questionsVotees.1": "question soutenue",
  "unite.questionsVotees.n": "questions soutenues",
  "unite.devoirsALHeure.1": "copie à l'heure",
  "unite.devoirsALHeure.n": "copies à l'heure",
  "unite.objectifs.1": "objectif du jour",
  "unite.objectifs.n": "objectifs du jour",

  // ── Ma progression (/progression, étudiant) ──
  "prog.titre": "Ma progression",
  "prog.intro": "Tes semaines, tes points et tes badges. Cette page n'est visible que par toi.",
  "prog.jours": "LMMJVSD",
  "prog.semaine.titre": "Ma semaine",
  "prog.semaine.compte": "{n}/{objectif} jours actifs",
  "prog.semaine.atteint": "Objectif atteint, bravo ! Chaque jour de plus compte encore pour ta classe.",
  "prog.semaine.reste1": "Encore 1 jour actif pour réussir ta semaine.",
  "prog.semaine.reste": "Encore {n} jours actifs pour réussir ta semaine.",
  "prog.semaine.aide": "Un jour compte dès que tu fais un acte d'apprentissage : révision, QCM, copie, émargement en salle, leçon…",
  "prog.semaine.aujourdhui": "aujourd'hui",
  "prog.objectif.titre": "Mon objectif de la semaine",
  "prog.objectif.option": "{n} jours",
  "prog.objectif.enregistre": "Objectif enregistré : {n} jours par semaine.",
  "prog.serie.titre": "Semaines réussies d'affilée",
  "prog.serie.record": "Record : {n}",
  "prog.serie.joker.libre": "Joker du mois disponible : il sauve tout seul une semaine où il te manque un jour.",
  "prog.serie.joker.pris": "Joker du mois déjà utilisé. Le prochain arrive le 1er du mois.",
  "prog.serie.derniere.reussie": "Semaine dernière réussie.",
  "prog.serie.derniere.joker": "Semaine dernière sauvée par ton joker.",
  "prog.serie.derniere.neutre": "Semaine dernière sans cours ni devoir : ta série reste intacte.",
  "prog.serie.derniere.manquee": "Semaine dernière manquée. Nouvelle semaine, nouveau départ.",
  "prog.points.titre": "Mes points",
  "prog.points.semaine": "points cette semaine",
  "prog.points.total": "{n} points depuis la rentrée",
  "prog.points.vide": "Pas encore de points cette semaine. Une révision ou un QCM suffit pour commencer.",
  "prog.points.fois": "×{n}",
  "prog.badges.titre": "Mes badges",
  "prog.badges.compte": "{n} sur {total}",
  "prog.badges.vide": "Ton premier badge arrive avec ton premier acte d'apprentissage.",
  "prog.badges.prochain": "Prochain badge",
  "prog.badges.aVenir": "À débloquer",
  "prog.classe.titre": "Ma contribution à la Coupe",
  "prog.classe.compte": "Cette semaine, tu comptes dans la participation de {classe}. Merci !",
  "prog.classe.compteCampus": "Cette semaine, tu comptes dans la participation de ton campus. Merci !",
  "prog.classe.reste1": "Encore 1 type d'acte cette semaine pour compter dans la participation de ta classe : une révision, un QCM, un émargement…",
  "prog.classe.reste2": "Deux types d'actes dans la semaine (par exemple un émargement et une révision) et tu comptes dans la participation de ta classe.",
  "prog.classe.lien": "Voir la Coupe",
  "prog.bareme.titre": "Comment gagner des points",
  "prog.bareme.presence": "Émarger en salle avec le QR de l'écran, ou suivre 30 min en ligne : +{n}, et +{m} au seuil de présence",
  "prog.bareme.devoir": "Rendre une copie : +{n} à l'heure, +{m} en retard",
  "prog.bareme.quiz": "Terminer une interrogation : +{n}, et +{m} avec au moins la moitié des points",
  "prog.bareme.revision": "Bonne réponse de révision : +{n} ({m} points par jour au plus)",
  "prog.bareme.entrainement": "Quiz d'entraînement d'un cours complet : +{n}",
  "prog.bareme.objectif": "Objectif du jour validé : +{n}",
  "prog.bareme.lecon": "Leçon terminée : +{n} ({m} par jour au plus)",
  "prog.bareme.direct": "En direct : question +{q} (+{v} si 3 camarades la soutiennent), sondage +{s}, ressenti +{r}",
  "prog.bareme.replay": "Replay d'un cours manqué, vraiment regardé : +{n}",
  "prog.bareme.jamais": "Ouvrir une page, rester connecté ou discuter avec l'assistant ne rapporte rien : seuls les actes d'apprentissage comptent.",
  "prog.erreur": "Ta progression n'a pas pu se charger.",

  // ── Nouveau badge ──
  "nouveau.titre1": "Nouveau badge !",
  "nouveau.titre": "{n} nouveaux badges !",
  "nouveau.ok": "Super !",

  // ── Pastille de l'accueil et gain du jour ──
  "pastille.libelle": "{n}/{objectif} j",
  "pastille.aria": "Ma semaine : {n} jours actifs sur {objectif}. Voir ma progression.",
  "gain.points": "+{n} points aujourd'hui",
  "gain.jour": "Jour actif ✓ · {n}/{objectif} cette semaine",
  "gain.semaine": "Semaine réussie ✓ · {n}/{objectif} jours",
  "gain.badge": "Nouveau badge : {nom}",
  "gain.lien": "Ma progression",

  // ── Coupe : commun ──
  "trophee.participation": "Participation",
  "trophee.progression": "Progression",
  "trophee.assiduite": "Assiduité au direct",
  "trophee.equipe": "Équipe",
  "trophee.participation.desc": "Le meilleur taux de chaque ligue.",
  "trophee.progression.desc": "La plus forte hausse sur la semaine précédente.",
  "trophee.assiduite.desc": "La meilleure présence aux directs émargés en salle.",
  "trophee.equipe.desc": "Toute classe où 70 % des étudiants participent.",
  "ligue.campus": "Campus",
  "ligue.annee1": "1re année",
  "ligue.annee2": "2e année",
  "ligue.licences": "Licences et certificats",
  "rang.1": "1er",
  "rang.n": "{n}e",

  // ── Coupe : page /coupe ──
  "coupe.titre": "Coupe des campus et des classes",
  "coupe.semaine": "Semaine {n}",
  "coupe.essai": "Semaine d'essai",
  "coupe.essai.aide": "Première semaine de la Coupe : le classement s'affiche, les trophées commencent la semaine prochaine.",
  "coupe.principe": {
    tu: "On compare des taux, pas des totaux : un petit campus peut gagner. Tout repart à zéro chaque lundi, et aucun nom d'étudiant n'est affiché.",
    vous: "Des taux, jamais des totaux ni des étudiants : un petit campus peut gagner, tout repart à zéro chaque lundi, et aucun nom d'étudiant n'apparaît.",
  },
  "coupe.maj": "Mis à jour à {heure}",
  "coupe.campus.titre": "Coupe des campus",
  "coupe.ligue.titre": "Ligue {ligue}",
  "coupe.autres": {
    tu: "Les autres, par ordre alphabétique, avec leur progression :",
    vous: "Les autres, par ordre alphabétique, avec leur progression :",
  },
  "coupe.bientot": "Bientôt dans la Coupe : {noms}",
  "coupe.hausse": "+{n} pts",
  "coupe.relance": "Tout se joue cette semaine",
  "coupe.score": "{n} %",
  "coupe.participation": "participation {n} %",
  "coupe.presence": "présence en salle {n} %",
  "coupe.moi.campus": { tu: "ton campus", vous: "votre campus" },
  "coupe.moi.classe": { tu: "ta classe", vous: "votre classe" },
  "coupe.maClasse.titre": "La quête de ta classe",
  "coupe.maClasse.quete": "{p} sur {i} ont participé cette semaine.",
  "coupe.maClasse.reste": "Encore {n} pour atteindre 70 % : trophée Équipe.",
  "coupe.maClasse.atteint": "70 % atteints : le trophée Équipe est en vue. Bravo à toute la classe !",
  "coupe.maClasse.petite": "Ta classe compte moins de 5 étudiants : elle joue avec ton campus dans la Coupe des campus.",
  "coupe.trophees.titre": "Les trophées de la semaine",
  "coupe.trophees.enTete": "En tête : {noms}",
  "coupe.trophees.personne": "Encore personne : à vous de jouer.",
  "coupe.trophees.essai": "Pas de trophée pendant la semaine d'essai.",
  "coupe.precedente": "Semaine {n} : les lauréats",
  "coupe.precedente.aucun": "Semaine {n} : aucun trophée attribué.",
  "coupe.comment.titre": "Comment ça marche ?",
  "coupe.comment.participer": {
    tu: "Tu participes quand tu fais au moins deux types d'actes dans la semaine : émarger au direct, rendre une copie, terminer un QCM, réviser…",
    vous: "Un étudiant participe quand il fait au moins deux types d'actes dans la semaine : émarger au direct, rendre une copie, terminer un QCM, réviser…",
  },
  "coupe.comment.salle": "Les campus qui émargent en salle comptent aussi leur présence aux directs ; une séance sans aucun émargement ne compte ni pour ni contre.",
  "coupe.comment.classes": "Ligues de classes de 5 étudiants ou plus, par niveau, tous campus confondus.",
  "coupe.vide": "Le classement de la semaine arrive dans quelques minutes.",
  "coupe.erreur": { tu: "La Coupe n'a pas pu se charger.", vous: "La Coupe n'a pas pu se charger." },

  // ── Coupe : vue de l'équipe ──
  "coupe.equipe.intro": "Vue de la direction et de la vie scolaire : tous les chiffres, y compris le bas des classements. Les étudiants ne voient que la moitié haute, et leur progression.",
  "coupe.col.score": "Taux",
  "coupe.col.participation": "Participation",
  "coupe.col.presence": "Présence en salle",
  "coupe.col.assidus": "Assidus (3 j)",
  "coupe.col.points": "Points moyens",
  "coupe.col.progression": "Progression",
  "coupe.col.inscrits": "Inscrits",
  "coupe.horsClassement": "hors classement (moins de 5 étudiants)",
  "coupe.nonMesure": "pas d'émargement",
  "coupe.seances1": "1 séance émargée",
  "coupe.seances": "{n} séances émargées",
  "coupe.horsClassement.voir": "Classes hors classement ({n})",
  "coupe.historique.titre": "Les 8 dernières semaines",
  "coupe.historique.col": "Campus et classes",
  "coupe.actes.titre": "Actes de la semaine, par campus",
  "coupe.actes.aucun": "Aucun acte enregistré cette semaine.",

  // ── Bandeau de l'accueil étudiant ──
  "bandeau.coupe": "Coupe · semaine {n}",
  "bandeau.meneur": "{nom} mène",
  "bandeau.monCampus": "{nom} {rang}",
  "bandeau.demarrage": "La semaine commence : chaque acte compte.",
  "bandeau.classe.hausse": "Ta classe progresse de +{n} points.",
  "bandeau.classe.relance": "Ta classe peut grimper : chaque acte compte.",

  // ── Écran de la salle de conférence ──
  "salle.titre": "Coupe des campus",
  "salle.semaine": "Semaine {n}",
  "salle.meneur": "{nom} mène cette semaine",
  "salle.demarrage": "La semaine commence : chaque émargement compte.",
  "salle.rang": "{nom} : {rang}",
  "salle.progression": "{nom} progresse de +{n} points",
  "salle.relance": "{nom} : chaque émargement compte cette semaine",
  "salle.bientot": "{nom} rejoindra la Coupe avec ses premiers étudiants.",
  "salle.emarger": "Émargez avec le QR de l'écran : chaque présence fait gagner votre campus.",

  // ── Cloche du lundi (sans rappel sur le téléphone) ──
  "notif.titre": "Coupe · semaine {n} : bravo !",
  "notif.classe": "Ta classe {classe} remporte : {trophees}.",
  "notif.campus": "Ton campus {campus} remporte : {trophees}.",
  "notif.merci": "Merci à chacun : c'est un succès collectif.",
});
