// Textes du chantier C4 : rappel d'entraînement du jour, relances des
// décrocheurs, e-mail « Ta semaine », page « Mes rappels », désabonnement et
// pilotage (couche commune : shared/textes/index.ts).
//
// Étudiants tutoyés, personnel vouvoyé. Ton : bienveillant et concret, une
// action courte à la clé, jamais de culpabilité, jamais de « série perdue ».
// On écrit « rappel », jamais « notification push ».
//
// Variantes : « rappel.cartes.3.titre » et « rappel.cartes.3.corps » forment
// la variante « cartes.3 ». Le serveur envoie la moins récemment employée
// (choisirVariante, shared/engagement/relances.ts) ; variantesDe() les liste.
import { creerTextes } from "./index";

const fr = {
  // ── Rappel d'entraînement : devoir dû dans les 30 h ─────────────────────
  // {cours} titre court du cours · {devoir} titre du devoir · {quand} « ce soir à 23h59 », « demain à 08h00 » · {detail} « 10 questions, environ 8 minutes »
  "rappel.devoir.quiz.1.titre": "Ton QCM de {cours} se ferme {quand}",
  "rappel.devoir.quiz.1.corps": "{detail}. Fais-le maintenant et c'est réglé.",
  "rappel.devoir.quiz.2.titre": "{detail} pour « {devoir} »",
  "rappel.devoir.quiz.2.corps": "Le QCM de {cours} se ferme {quand}. Un bon moment pour t'y mettre ?",
  "rappel.devoir.quiz.3.titre": "QCM de {cours} : dernière ligne droite",
  "rappel.devoir.quiz.3.corps": "Il se ferme {quand}. {detail}, et ta note est tout de suite là.",
  "rappel.devoir.quiz.4.titre": "« {devoir} » t'attend",
  "rappel.devoir.quiz.4.corps": "{detail}. Il reste ouvert jusqu'à {quand}.",
  "rappel.devoir.quiz.5.titre": "Un QCM rapide avant {quand} ?",
  "rappel.devoir.quiz.5.corps": "{cours} : {detail}. Tu peux le faire d'ici, sur ton téléphone.",
  "rappel.devoir.quiz.6.titre": "Ton QCM de {cours}, c'est le moment",
  "rappel.devoir.quiz.6.corps": "Ouvert jusqu'à {quand}. {detail} : le temps d'une pause.",
  "rappel.devoir.quiz.7.titre": "{cours} : ton QCM se ferme {quand}",
  "rappel.devoir.quiz.7.corps": "« {devoir} » : {detail}. Lance-toi, tu connais le cours.",
  "rappel.devoir.quiz.8.titre": "Le QCM « {devoir} » est encore ouvert",
  "rappel.devoir.quiz.8.corps": "Jusqu'à {quand}. {detail}, sans rien à télécharger.",
  "rappel.devoir.quiz.9.titre": "Avant {quand} : ton QCM de {cours}",
  "rappel.devoir.quiz.9.corps": "{detail}. Une fois fait, tu n'y penses plus.",
  "rappel.devoir.quiz.10.titre": "Et si tu faisais le QCM de {cours} ?",
  "rappel.devoir.quiz.10.corps": "« {devoir} » se ferme {quand}. {detail}.",

  "rappel.devoir.depot.1.titre": "Ton devoir de {cours} est à rendre {quand}",
  "rappel.devoir.depot.1.corps": "« {devoir} » : une photo de ta copie suffit pour le rendre.",
  "rappel.devoir.depot.2.titre": "« {devoir} » : à rendre {quand}",
  "rappel.devoir.depot.2.corps": "Prends ta copie en photo depuis le campus, c'est envoyé même avec peu de réseau.",
  "rappel.devoir.depot.3.titre": "Dernière ligne droite pour « {devoir} »",
  "rappel.devoir.depot.3.corps": "{cours} : la remise ferme {quand}. Tu y es presque.",
  "rappel.devoir.depot.4.titre": "Ton devoir de {cours} t'attend",
  "rappel.devoir.depot.4.corps": "À rendre {quand}. Un texte, une photo ou un PDF : comme tu préfères.",
  "rappel.devoir.depot.5.titre": "Un petit moment pour « {devoir} » ?",
  "rappel.devoir.depot.5.corps": "La remise de {cours} ferme {quand}. Ton reçu arrive dès l'envoi.",
  "rappel.devoir.depot.6.titre": "{cours} : ton devoir, c'est pour {quand}",
  "rappel.devoir.depot.6.corps": "Rends « {devoir} » en quelques gestes, depuis ton téléphone.",
  "rappel.devoir.depot.7.titre": "« {devoir} » se rend {quand}",
  "rappel.devoir.depot.7.corps": "Tu peux préparer ta copie même hors ligne : elle part au retour du réseau.",
  "rappel.devoir.depot.8.titre": "Avant {quand} : ton devoir de {cours}",
  "rappel.devoir.depot.8.corps": "Une fois rendu, tu reçois ton reçu tout de suite.",
  "rappel.devoir.depot.9.titre": "Ton devoir « {devoir} » est presque dû",
  "rappel.devoir.depot.9.corps": "Il reste jusqu'à {quand}. Une photo nette de ta copie suffit.",
  "rappel.devoir.depot.10.titre": "On boucle « {devoir} » ?",
  "rappel.devoir.depot.10.corps": "{cours} : remise {quand}. Quelques minutes et c'est fait.",

  // ── Rattrapage : séance où il n'a pas été compté présent (jamais « inconnu »), cours complet prêt ──
  // On dit ce qu'on sait (sa présence n'a pas été relevée), jamais « tu as manqué » : il a pu être en salle sans scanner.
  // {cours} · {jour} « mercredi »
  "rappel.rattrapage.1.titre": "Ta présence n'a pas été relevée {jour}",
  "rappel.rattrapage.1.corps": "Le cours complet de {cours} est prêt : 15 minutes, sans vidéo. Tu étais en salle ? Dis-le à la vie scolaire.",
  "rappel.rattrapage.2.titre": "Le cours de {cours} de {jour}, en 15 minutes",
  "rappel.rattrapage.2.corps": "L'essentiel, les fiches et un petit quiz, à lire tranquillement.",
  "rappel.rattrapage.3.titre": "Rattrape {cours} sans regarder la vidéo",
  "rappel.rattrapage.3.corps": "Le cours de {jour} est résumé pour toi. Lis-le à ton rythme.",
  "rappel.rattrapage.4.titre": "Le cours de {jour} t'attend",
  "rappel.rattrapage.4.corps": "Le cours complet de {cours} t'attend : 15 minutes suffisent pour être à jour.",
  "rappel.rattrapage.5.titre": "{cours} : le cours de {jour} est prêt",
  "rappel.rattrapage.5.corps": "Une lecture légère, faite pour le téléphone. Tu seras à jour pour la suite.",
  "rappel.rattrapage.6.titre": "Remets-toi à jour en {cours}",
  "rappel.rattrapage.6.corps": "Le cours de {jour} tient en 15 minutes de lecture, quiz compris.",
  "rappel.rattrapage.7.titre": "Le cours de {jour}, version courte",
  "rappel.rattrapage.7.corps": "{cours} : à retenir, fiches et exercices. Commence par « À retenir ».",
  "rappel.rattrapage.8.titre": "15 minutes pour rattraper {cours}",
  "rappel.rattrapage.8.corps": "Le cours de {jour} est déjà écrit pour toi, sans vidéo à charger.",
  "rappel.rattrapage.9.titre": "Le résumé du cours de {jour} t'attend",
  "rappel.rattrapage.9.corps": "{cours} en quelques pages. Idéal pour revenir dans le rythme.",
  "rappel.rattrapage.10.titre": "On rattrape {cours} ensemble ?",
  "rappel.rattrapage.10.corps": "Le cours complet de {jour} est prêt. Lis l'essentiel, puis fais le quiz.",

  // ── Cartes de révision dues (chantier C1) ── {n} cartes · {minutes}
  "rappel.cartes.1.titre": "{n} cartes à revoir aujourd'hui · {minutes} min",
  "rappel.cartes.1.corps": "Juste ce qu'il faut pour que tes cours restent en mémoire.",
  "rappel.cartes.2.titre": "Ta révision du jour est prête",
  "rappel.cartes.2.corps": "{n} cartes, environ {minutes} minutes. Même sans réseau.",
  "rappel.cartes.3.titre": "{minutes} minutes pour garder tes cours en tête",
  "rappel.cartes.3.corps": "{n} cartes t'attendent : c'est le bon moment pour les revoir.",
  "rappel.cartes.4.titre": "Tes cartes sont prêtes",
  "rappel.cartes.4.corps": "{n} questions de tes derniers cours, revues au bon moment.",
  "rappel.cartes.5.titre": "Une petite révision avant ce soir ?",
  "rappel.cartes.5.corps": "{n} cartes, {minutes} minutes. Tu verras, ça rentre vite.",
  "rappel.cartes.6.titre": "{n} cartes, et ta journée de révision est faite",
  "rappel.cartes.6.corps": "Retourne-les une par une : « Je savais » ou « À revoir ».",
  "rappel.cartes.7.titre": "Révise pendant que c'est frais",
  "rappel.cartes.7.corps": "{n} cartes de tes cours t'attendent, environ {minutes} minutes.",
  "rappel.cartes.8.titre": "Ta mémoire te dira merci",
  "rappel.cartes.8.corps": "{n} cartes à revoir aujourd'hui. Pas de note, juste de l'entraînement.",
  "rappel.cartes.9.titre": "{minutes} min de révision ?",
  "rappel.cartes.9.corps": "{n} cartes sont dues aujourd'hui. Le paquet est déjà sur ton téléphone.",
  "rappel.cartes.10.titre": "Les cartes du jour sont là",
  "rappel.cartes.10.corps": "{n} questions, revues juste avant de les oublier.",

  // ── Objectif du jour pas fini (chantier C2) ── {reste} éléments restants · {total}
  "rappel.objectif_jour.1.titre": "Encore {reste} sur {total} pour valider ta journée",
  "rappel.objectif_jour.1.corps": "Ton objectif du jour est presque atteint. Termine-le en quelques minutes.",
  "rappel.objectif_jour.2.titre": "Ton objectif du jour t'attend",
  "rappel.objectif_jour.2.corps": "Il te reste {reste} sur {total}. Chaque ligne est courte.",
  "rappel.objectif_jour.3.titre": "Presque fini pour aujourd'hui",
  "rappel.objectif_jour.3.corps": "{reste} sur {total} encore, et ta journée est validée.",
  "rappel.objectif_jour.4.titre": "Plus que {reste} sur {total} avant ce soir",
  "rappel.objectif_jour.4.corps": "Ouvre ton objectif du jour : tout est prêt, tu n'as qu'à suivre.",
  "rappel.objectif_jour.5.titre": "Ta journée de campus se termine bien ?",
  "rappel.objectif_jour.5.corps": "Il reste {reste} sur {total} à ton objectif du jour.",
  "rappel.objectif_jour.6.titre": "On valide ta journée ?",
  "rappel.objectif_jour.6.corps": "Encore {reste} sur {total}. Quelques minutes suffisent.",
  "rappel.objectif_jour.7.titre": "Ton objectif du jour, la suite",
  "rappel.objectif_jour.7.corps": "{reste} sur {total} à faire. Le plus dur est derrière toi.",
  "rappel.objectif_jour.8.titre": "{reste} sur {total} pour aujourd'hui",
  "rappel.objectif_jour.8.corps": "Finis ton objectif du jour pendant qu'il est encore temps.",
  "rappel.objectif_jour.9.titre": "Il te manque {reste} sur {total}",
  "rappel.objectif_jour.9.corps": "Ton objectif du jour est fait pour tenir dans une pause.",
  "rappel.objectif_jour.10.titre": "Un dernier effort pour aujourd'hui",
  "rappel.objectif_jour.10.corps": "{reste} sur {total} à ton objectif du jour, et c'est validé.",

  // ── Objectif de la semaine à un jour près (chantier C5) ── {faits} jours actifs · {objectif}
  "rappel.objectif_semaine.1.titre": "{faits} sur {objectif} jours cette semaine",
  "rappel.objectif_semaine.1.corps": "Un de plus et c'est gagné. Une révision ou un QCM suffit.",
  "rappel.objectif_semaine.2.titre": "Ta semaine est presque réussie",
  "rappel.objectif_semaine.2.corps": "{faits} sur {objectif} jours : il ne t'en manque qu'un.",
  "rappel.objectif_semaine.3.titre": "Plus qu'un jour pour réussir ta semaine",
  "rappel.objectif_semaine.3.corps": "Tu en es à {faits} sur {objectif}. Aujourd'hui peut être le bon.",
  "rappel.objectif_semaine.4.titre": "{faits} sur {objectif} : un dernier jour ?",
  "rappel.objectif_semaine.4.corps": "Quelques minutes d'entraînement aujourd'hui et ta semaine est réussie.",
  "rappel.objectif_semaine.5.titre": "Ta semaine se joue aujourd'hui",
  "rappel.objectif_semaine.5.corps": "{faits} sur {objectif} jours actifs. Un petit geste, et c'est fait.",
  "rappel.objectif_semaine.6.titre": "Encore un jour et ta semaine est gagnée",
  "rappel.objectif_semaine.6.corps": "Tu as déjà {faits} sur {objectif} jours. Bravo, continue.",
  "rappel.objectif_semaine.7.titre": "Belle semaine : {faits} sur {objectif} jours",
  "rappel.objectif_semaine.7.corps": "Il manque un jour. Une carte, un QCM ou un cours complet compte.",
  "rappel.objectif_semaine.8.titre": "Un jour de plus pour ta semaine ?",
  "rappel.objectif_semaine.8.corps": "{faits} sur {objectif} : tu touches au but.",
  "rappel.objectif_semaine.9.titre": "Ton objectif de la semaine est à portée",
  "rappel.objectif_semaine.9.corps": "{faits} sur {objectif} jours déjà faits. Aujourd'hui compte.",
  "rappel.objectif_semaine.10.titre": "On termine la semaine en beauté ?",
  "rappel.objectif_semaine.10.corps": "{faits} sur {objectif} jours. Un de plus et la semaine est à toi.",

  // ── Cours complet récent pas encore ouvert ── {cours} · {quand} « d'hier », « de mardi »
  "rappel.cours_complet.1.titre": "Le cours complet {quand} est prêt",
  "rappel.cours_complet.1.corps": "{cours} : l'essentiel, les fiches et un quiz, en 10 minutes.",
  "rappel.cours_complet.2.titre": "{cours} : relis l'essentiel en 10 minutes",
  "rappel.cours_complet.2.corps": "Le cours {quand} est résumé pour toi, sans vidéo à charger.",
  "rappel.cours_complet.3.titre": "Ton cours {quand}, en version courte",
  "rappel.cours_complet.3.corps": "{cours} : commence par « À retenir », puis fais le quiz.",
  "rappel.cours_complet.4.titre": "10 minutes pour fixer le cours {quand}",
  "rappel.cours_complet.4.corps": "Relire le lendemain, c'est ce qui fait tenir un cours en mémoire.",
  "rappel.cours_complet.5.titre": "Le cours de {cours} t'attend",
  "rappel.cours_complet.5.corps": "Le cours complet {quand} est prêt : fiches, glossaire et quiz.",
  "rappel.cours_complet.6.titre": "Un quiz sur le cours {quand} ?",
  "rappel.cours_complet.6.corps": "{cours} : le cours complet a son quiz d'entraînement. Pas de note.",
  "rappel.cours_complet.7.titre": "Relis {cours} pendant que c'est frais",
  "rappel.cours_complet.7.corps": "Le cours {quand} tient en quelques pages, faites pour le téléphone.",
  "rappel.cours_complet.8.titre": "Ce qu'il faut retenir du cours {quand}",
  "rappel.cours_complet.8.corps": "{cours} : cinq minutes pour l'essentiel, cinq de plus pour le quiz.",
  "rappel.cours_complet.9.titre": "Le résumé de {cours} est prêt",
  "rappel.cours_complet.9.corps": "Le cours {quand}, écrit pour toi. Lis-le à ton rythme.",
  "rappel.cours_complet.10.titre": "Et si tu revoyais le cours {quand} ?",
  "rappel.cours_complet.10.corps": "{cours} : l'essentiel en 10 minutes, avec un quiz pour vérifier.",

  // ── Dernier message honnête, après 5 rappels ignorés ──
  "rappel.lassitude.1.titre": "On fait une pause dans les rappels",
  "rappel.lassitude.1.corps": "Tu n'as pas ouvert nos derniers rappels : on arrête de t'en envoyer. Ils reviendront dès que tu reprendras.",
  "rappel.lassitude.2.titre": "Plus de rappel d'entraînement pour l'instant",
  "rappel.lassitude.2.corps": "On ne veut pas t'encombrer. Dès que tu reviens sur le campus, ils reprennent à ton heure.",
  "rappel.lassitude.3.titre": "On te laisse tranquille un moment",
  "rappel.lassitude.3.corps": "Nos rappels d'entraînement s'arrêtent. Tu peux choisir une autre heure dans « Mes rappels ».",

  // ── Décrocheurs, palier 1 : un rappel doux et utile ──
  // On dit seulement ce qu'on mesure (rien sur le campus numérique), jamais « on ne t'a pas vu » :
  // il suit peut-être ses cours en salle sans être émargé.
  // {n} jours sans activité · {action} prochaine action concrète (phrase complète)
  "relance.inactif.1.titre": "Tes révisions t'attendent sur ton téléphone",
  "relance.inactif.1.corps": "{action}",
  "relance.inactif.2.titre": "Rien sur ton campus numérique depuis {n} jours : on reprend ?",
  "relance.inactif.2.corps": "{action} Reprends en douceur, à ton rythme.",
  "relance.inactif.3.titre": "Ton campus numérique t'attend",
  "relance.inactif.3.corps": "Pas besoin de tout rattraper d'un coup. {action}",
  "relance.inactif.4.titre": "Un petit pas pour reprendre ?",
  "relance.inactif.4.corps": "{action} Quelques minutes suffisent.",
  "relance.inactif.5.titre": "Ça fait {n} jours : on reprend ensemble ?",
  "relance.inactif.5.corps": "{action}",
  "relance.inactif.6.titre": "Tes cours continuent, et tout est prêt pour toi",
  "relance.inactif.6.corps": "{action} Un souci de téléphone ou de réseau ? Écris à la vie scolaire.",

  "relance.devoir_non_rendu.1.titre": "Il est encore temps pour « {devoir} »",
  "relance.devoir_non_rendu.1.corps": "Ton devoir de {cours} peut encore être rendu. Une photo de ta copie suffit.",
  "relance.devoir_non_rendu.2.titre": "« {devoir} » : tu peux encore le rendre",
  "relance.devoir_non_rendu.2.corps": "{cours} accepte les copies en retard. Mieux vaut tard que jamais.",
  "relance.devoir_non_rendu.3.titre": "Ton devoir de {cours} t'attend toujours",
  "relance.devoir_non_rendu.3.corps": "Rends « {devoir} » depuis ton téléphone, en quelques gestes.",
  "relance.devoir_non_rendu.4.titre": "Un coup de main pour « {devoir} » ?",
  "relance.devoir_non_rendu.4.corps": "La remise reste ouverte. Si quelque chose bloque, écris à ton formateur.",

  "relance.lives_manques.1.titre": "Les deux derniers cours de {cours} t'attendent",
  "relance.lives_manques.1.corps": "Rattrape-les sur ton téléphone, à ton rythme. Si tu étais en salle, pense à scanner le QR de l'écran.",
  "relance.lives_manques.2.titre": "On t'a gardé les cours de {cours}",
  "relance.lives_manques.2.corps": "Tout est sur le campus : l'essentiel à lire et le replay. La prochaine fois en salle, scanne le QR : ta présence sera comptée.",
  "relance.lives_manques.3.titre": "{cours} : les deux derniers cours sont résumés pour toi",
  "relance.lives_manques.3.corps": "Ta présence n'y a pas été relevée. Si tu étais bien là, dis-le à la vie scolaire.",
  "relance.lives_manques.4.titre": "Remets-toi à jour en {cours}",
  "relance.lives_manques.4.corps": "Les deux derniers cours t'attendent sur le campus. Si tu étais en salle, pense à émarger la prochaine fois.",

  // Prochaine action concrète, glissée dans les relances. Phrases complètes.
  "action.devoir": "Ton devoir « {devoir} » ({cours}) est à rendre {quand}.",
  "action.cours_complet": "Le cours complet de {cours} est prêt : l'essentiel en 10 minutes.",
  "action.cartes": "{n} cartes de révision t'attendent : 3 minutes.",
  "action.defaut": "Ouvre ton campus : tes cours, tes replays et tes devoirs t'attendent.",

  // ── Décrocheurs, palier 2 : l'e-mail ──
  "email.relance.etiquette": "Campus numérique · On pense à toi",
  "email.relance.titre": "Bonjour {prenom},",
  "email.relance.inactif.sujet": "{prenom}, ton campus numérique t'attend",
  "email.relance.inactif.p1": "Aucune activité sur ton campus numérique depuis {n} jours (révision, QCM, devoir, cours complet). Pas d'inquiétude : tout est encore là, et rien n'est perdu.",
  "email.relance.inactif.p2": "Pour reprendre en douceur, commence par ceci. {action}",
  "email.relance.devoir_non_rendu.sujet": "« {devoir} » : tu peux encore le rendre",
  "email.relance.devoir_non_rendu.p1": "Ton devoir **« {devoir} »** ({cours}) n'a pas encore été rendu, et la remise est encore ouverte.",
  "email.relance.devoir_non_rendu.p2": "Ouvre le campus, touche « Rendre mon devoir » et prends ta copie en photo : c'est fait en quelques minutes.",
  "email.relance.lives_manques.sujet": "Les cours de {cours} t'attendent",
  "email.relance.lives_manques.p1": "Ta présence n'a pas été relevée aux deux derniers cours de **{cours}**. Tout t'attend sur le campus : le replay et, dès qu'il est prêt, le cours complet, l'essentiel en 15 minutes, sans vidéo.",
  "email.relance.lives_manques.p2": "Si tu étais en salle, pense à scanner le QR de l'écran au début du cours : c'est lui qui relève ta présence.",
  "email.relance.aide": "Un souci de téléphone, de réseau ou de code secret ? Écris sur WhatsApp à la vie scolaire de ton campus : on trouvera une solution.",
  "email.relance.bouton": "Reprendre sur le campus",

  // ── E-mail du lundi « Ta semaine au campus » ──
  "email.semaine.sujet": "Ta semaine au campus · {resume}",
  "email.semaine.sujet.vide": "Ta semaine au campus commence",
  "email.semaine.etiquette": "Ta semaine · du {du} au {au}",
  "email.semaine.titre": "Bonjour {prenom},",
  "email.semaine.apercu": "Ce que tu as fait, et ce qui t'attend cette semaine.",
  "email.semaine.intro.actif": "La semaine dernière, tu as travaillé {jours} jours sur le campus. Beau travail, continue comme ça.",
  "email.semaine.intro.actif.un": "La semaine dernière, tu as travaillé un jour sur le campus. Chaque jour compte : cette semaine, vise-en un de plus.",
  "email.semaine.intro.calme": "La semaine dernière a été calme sur le campus. Cette semaine est une nouvelle page : voici ce qui t'attend.",
  "email.semaine.section.passee": "Ta semaine passée",
  "email.semaine.ligne.jours": "{n} jours de travail sur 7",
  "email.semaine.ligne.jours.un": "1 jour de travail sur 7",
  "email.semaine.ligne.rendus": "{n} copies rendues",
  "email.semaine.ligne.rendus.un": "1 copie rendue",
  "email.semaine.ligne.quiz": "{n} QCM terminés",
  "email.semaine.ligne.quiz.un": "1 QCM terminé",
  "email.semaine.ligne.directs": "{n} cours en direct suivis",
  "email.semaine.ligne.directs.un": "1 cours en direct suivi",
  "email.semaine.ligne.replays": "{n} replays ou cours complets ouverts",
  "email.semaine.ligne.replays.un": "1 replay ou cours complet ouvert",
  "email.semaine.ligne.revisions": "{n} cartes révisées",
  "email.semaine.ligne.revisions.un": "1 carte révisée",
  "email.semaine.ligne.points": "{n} points gagnés",
  "email.semaine.ligne.points.un": "1 point gagné",
  "email.semaine.section.directs": "Tes cours en direct cette semaine",
  "email.semaine.ligne.direct": "{jour} à {heure} · {cours} : {titre}",
  "email.semaine.section.echeances": "À rendre cette semaine",
  "email.semaine.ligne.echeance": "{devoir} ({cours}) · avant {quand}",
  "email.semaine.section.cours_complets": "Cours complets à lire",
  "email.semaine.ligne.cours_complet": "{cours} : {titre}",
  "email.semaine.section.coupe": "Ta classe et ton campus",
  "email.semaine.ligne.classe": "Ta classe : {rang} sur {total}, {taux} % de participation",
  "email.semaine.ligne.campus": "Campus {campus} : {rang} sur {total}, {taux} % de participation",
  // Hors de la moitié haute : jamais de rang (aucun « dernier »), seulement une progression positive. {n} points de pourcentage.
  "email.semaine.ligne.classe.progres": "Ta classe progresse dans la Coupe : +{n} points de % sur la semaine d'avant",
  "email.semaine.ligne.campus.progres": "Campus {campus} : en progrès dans la Coupe, +{n} points de % sur la semaine d'avant",
  "email.semaine.rien": "Rien de prévu pour l'instant : profites-en pour relire un cours complet.",
  "email.semaine.bouton": "Ouvrir mon campus",
  "email.semaine.apres": "Tes rappels arrivent sur ton téléphone ; cet e-mail, une fois par semaine, le lundi matin.",

  // Pied des e-mails d'engagement (lien signé, sans connexion)
  "email.desinscription.raison": "Tu reçois cet e-mail parce que tu as un compte sur le campus numérique 2IAE.",
  "email.desinscription.lien": "Ne plus recevoir ces e-mails",

  // ── Page « Mes rappels » (étudiant) ──
  "page.etiquette": "Ton compte",
  "page.titre": "Mes rappels",
  "page.sous_titre": "Un rappel d'entraînement par jour au plus, à ton heure, jamais la nuit.",
  "page.heure.titre": "Heure du rappel d'entraînement",
  "page.heure.description": "Il part seulement si tu n'as pas encore travaillé ce jour-là, et jamais pendant un cours en direct.",
  "page.heure.auto": "Automatique",
  "page.heure.auto_detail": "Vers {heure}, l'heure où tu travailles d'habitude.",
  "page.heure.auto_defaut": "Vers {heure}, tant que le campus ne connaît pas encore tes habitudes.",
  "page.heure.choisie": "À {heure} chaque jour.",
  "page.heure.choisir": "Choisir…",
  "page.actifs.titre": "Rappels d'entraînement",
  "page.actifs.description": "Une révision, un QCM qui se ferme, un cours à rattraper : une seule idée par jour.",
  "page.pause.titre": "Faire une pause",
  "page.pause.description": "Plus de rappel d'entraînement pendant 7 jours. Les rappels de cours et de devoirs continuent.",
  "page.pause.bouton": "Pause de 7 jours",
  "page.pause.en_cours": "En pause jusqu'au {jour} inclus.",
  "page.pause.reprendre": "Reprendre maintenant",
  "page.pause_auto": "Tes rappels d'entraînement sont en pause : tu ne les ouvrais plus. Ils reprennent dès que tu travailles sur le campus, ou tout de suite si tu touches « Reprendre ».",
  "page.pause_auto.reprendre": "Reprendre",
  "page.emails.titre": "E-mails",
  "page.emails.description": "« Ta semaine au campus », le lundi matin, et un mot si tu ne fais plus rien sur le campus numérique.",
  "page.emails.sans_adresse": "Ajoute ton adresse e-mail dans ton profil pour recevoir « Ta semaine au campus ».",
  "page.emails.ajouter": "Ajouter mon e-mail",
  "page.telephone.non": "Ce téléphone ne reçoit pas encore les rappels.",
  "page.telephone.activer": "Activer les rappels",
  "page.temoin": "Certains jours, tirés au sort, le campus n'envoie pas le rappel d'entraînement : c'est pour vérifier qu'il t'aide. Les rappels de cours et de devoirs, eux, arrivent toujours.",
  "page.enregistre": "C'est enregistré.",
  "page.profil.titre": "Mes rappels",
  "page.profil.description": "L'heure de ton rappel d'entraînement, une pause, et tes e-mails.",
  "page.profil.ouvrir": "Régler",

  // ── Désabonnement (lien de l'e-mail, sans connexion) ──
  // Le lien de l'e-mail mène d'abord à « confirmer » : un analyseur de liens qui l'ouvre ne désabonne personne.
  "desabonnement.titre.confirmer": "Ne plus recevoir nos e-mails ?",
  "desabonnement.texte.confirmer": "Tu ne recevrais plus « Ta semaine au campus » ni nos relances par e-mail. Les e-mails importants (code secret, inscription) continuent.",
  "desabonnement.confirmer": "Ne plus recevoir ces e-mails",
  "desabonnement.titre.fait": "C'est fait",
  "desabonnement.texte.fait": "Tu ne recevras plus les e-mails « Ta semaine au campus » ni nos relances par e-mail. Les e-mails importants (code secret, inscription) continuent.",
  "desabonnement.titre.reabonne": "C'est noté",
  "desabonnement.texte.reabonne": "Tu recevras de nouveau « Ta semaine au campus », le lundi matin.",
  "desabonnement.titre.invalide": "Ce lien ne marche pas",
  "desabonnement.texte.invalide": "Il est incomplet ou a été modifié. Tu peux régler tes e-mails dans « Mes rappels », depuis ton profil.",
  "desabonnement.reabonner": "Finalement, je veux les recevoir",
  "desabonnement.campus": "Ouvrir mon campus",

  // ── Pilotage (personnel, vouvoyé) ──
  "pilotage.titre": "Relances automatiques",
  "pilotage.description": "Rappel d'entraînement du jour, relances des décrocheurs (un rappel, puis un e-mail, puis la vie scolaire) et e-mail du lundi. En essai, tout est calculé et affiché, rien ne part.",
  "pilotage.rappels": "Rappel d'entraînement",
  "pilotage.relances": "Relances des décrocheurs",
  "pilotage.emails": "E-mails",
  "pilotage.plafond": "E-mails par jour au plus",
  "pilotage.plafond.aide": "Le compte d'envoi est partagé avec www.2iae.com : ce qui dépasse part le lendemain. Un quart est gardé aux e-mails des décrocheurs.",
  "pilotage.mode.essai": "En essai",
  "pilotage.mode.actif": "En marche",
  "pilotage.mode.pause": "En pause",
  "pilotage.mode_emails.essai": "En essai",
  "pilotage.mode_emails.actif": "En marche",
  "pilotage.enregistrer": "Enregistrer",
  "pilotage.enregistre": "Réglage enregistré.",
  "pilotage.etat.rappels": "Rappel d'entraînement : {mode}",
  "pilotage.etat.relances": "Relances : {mode}",
  "pilotage.etat.emails": "E-mails : {mode}",
  "pilotage.etat.essai": "en essai",
  "pilotage.etat.actif": "en marche",
  "pilotage.etat.pause": "en pause",
  "pilotage.note.essai": "En essai, tout est calculé et affiché ici ; rien ne part.",
  "pilotage.stat.rappels": "Rappels d'entraînement · 7 j",
  "pilotage.stat.relances": "Relances · 7 j",
  "pilotage.stat.revenus": "Revenus sous 48 h",
  "pilotage.stat.appeler": "À appeler",
  "pilotage.stat.emails": "E-mails aujourd'hui",
  "pilotage.stat.semaine": "E-mails du lundi · 7 j",
  "pilotage.semaine_sans_email": "{n} étudiants n'ont pas encore reçu « Ta semaine » cette semaine : le plafond d'e-mails est atteint. Augmentez-le si votre forfait d'envoi le permet.",
  "pilotage.semaine_sans_email.un": "1 étudiant n'a pas encore reçu « Ta semaine » cette semaine : le plafond d'e-mails est atteint. Augmentez-le si votre forfait d'envoi le permet.",
  "pilotage.maj": "Réglé le {date} par {qui}.",
  "pilotage.filtre": "À appeler",
  "pilotage.a_appeler.vide.titre": "Personne à appeler pour l'instant.",
  "pilotage.a_appeler.vide.texte": "Un étudiant arrive ici après deux relances automatiques restées sans effet (un rappel, puis un e-mail).",
  "pilotage.a_appeler.essai": "Relances en essai : aucune relance n'est partie, la liste montre qui serait à appeler.",
  "pilotage.a_appeler.texte": "Relances automatiques restées sans effet : {liste}.",
  "pilotage.a_appeler.action": "Appeler l'étudiant pour comprendre ce qui bloque (réseau, téléphone, code secret ?)",
  "pilotage.a_appeler.relance": "{canal} le {jour}",
  // Message WhatsApp proposé à la vie scolaire (au tutoiement : il s'adresse à l'étudiant). {entree} « Bonjour Awa, … »
  "pilotage.a_appeler.whatsapp": "{entree} Tu n'as rien fait sur le campus numérique depuis quelques jours (révision, QCM, devoir). Tout va bien ? Si quelque chose t'empêche de suivre (réseau, téléphone, code secret), dis-le-nous : on trouvera une solution.",

  // État d'un étudiant dans « Qui décroche ? »
  "etat.relance": "Relancé le {jour} ({canal})",
  "etat.relance.essai": "Aurait été relancé le {jour} ({canal}) · essai",
  "etat.revenu": "revenu le {jour} ✓",
  "etat.revenu.depuis": "revenu depuis ✓",
  "etat.attente": "pas encore revenu",
  "etat.a_appeler": "{n} relances sans effet : à appeler",
  "etat.a_appeler.un": "1 relance sans effet : à appeler",
  "etat.a_appeler.aucune": "Aucune relance n'a pu partir : à appeler",
  "etat.a_appeler.essai": "Serait à appeler (essai : rien n'est parti)",
  "etat.historique": "Historique des relances",
  "etat.historique.masquer": "Masquer l'historique",
  "etat.historique.vide": "Aucune relance automatique.",
  "canal.push": "rappel",
  "canal.email": "e-mail",
  "canal.vie_scolaire": "vie scolaire",
  "motif.rappel_du_jour": "Rappel d'entraînement",
  "motif.inactif": "Sans activité en ligne",
  "motif.devoir_non_rendu": "Devoir non rendu",
  "motif.lives_manques": "Présence non relevée à 2 directs",
  "motif.semaine": "E-mail de la semaine",
  "statut.simulation": "essai",
  "statut.envoye": "envoyé",
  "statut.plafond": "plafond du jour",
  "statut.sans_canal": "injoignable",
  "statut.temoin": "jour témoin",
  "statut.quota": "reporté (quota)",
  "statut.echec": "échec d'envoi",
  "statut.pause_auto": "pause automatique",
  "statut.a_appeler": "à appeler",
} as const;

export type CleRelances = keyof typeof fr;
export const t = creerTextes(fr);

/**
 * Variantes d'une famille (« rappel.cartes » → ["cartes.1", …, "cartes.10"]) :
 * celles dont le titre et le corps existent, dans l'ordre des numéros.
 */
export function variantesDe(famille: string): string[] {
  const motif = new RegExp(`^${famille.replace(/\./g, "\\.")}\\.(\\d+)\\.titre$`);
  const prefixe = famille.split(".").slice(1).join(".");
  return Object.keys(fr)
    .map((cle) => motif.exec(cle)?.[1])
    .filter((n): n is string => Boolean(n) && `${famille}.${n}.corps` in fr)
    .sort((a, b) => Number(a) - Number(b))
    .map((n) => `${prefixe}.${n}`);
}
