// Textes de « Le travail du campus » (demande de José du 8 octobre 2026 au soir) : l'accueil simplifié du
// formateur (« Ma prochaine classe », « À faire », « Mes séances »), la carte d'une séance tenue (CarteSeance)
// et la page de la direction (/pilotage/travail). Des mots de tous les jours, un mot par chose : « Cours
// résumé » (jamais « cours complet » à l'écran), « Vidéo du cours », « QCM », « Exercice », « Corrigé »,
// « Ma classe ». Formateurs et équipe vouvoyés. Couche commune : shared/textes/index.ts ; un texte « .un » /
// « .n » (et « .zero ») se choisit selon le nombre avec selonNombre().
import { creerTextes, type Dictionnaire, type OptionsTexte, type Traducteur } from "./index";

const FR = {
  // ── Accueil du formateur : « Ma prochaine classe » ─────────────────────────
  "classe.etiquette": "Ma prochaine classe",
  "classe.etiquette.direct": "Votre classe est ouverte",
  "classe.etiquette.attente": "C'est l'heure",
  "classe.entrer": "Entrer dans ma classe",
  "classe.preparer": "Préparer mon cours",
  "classe.lien.entrer": "Entrer dans ma classe maintenant",
  "classe.lien.preparer": "Revoir ma préparation",
  "classe.abidjan": "heure d'Abidjan",
  "classe.chezVous": "{heure} chez vous ({ville})",
  "classe.dans": "dans",
  "classe.attendent": "Vos étudiants vous attendent.",
  "classe.ensuite": "Ensuite : {titre}, {quand}",
  "classe.aucune.titre": "Pas de cours prévu",
  "classe.aucune.texte": "Votre prochaine classe s'affichera ici dès que la direction l'aura programmée.",
  "classe.aucune.emploi": "Voir mon emploi du temps",
  "classe.reglages": "Avant le cours : lieu, essai de la visio, diapos",

  // ── Accueil du formateur : « À faire » ─────────────────────────────────────
  "afaire.titre": "À faire",
  "afaire.corriges.un": "1 corrigé à vérifier",
  "afaire.corriges.n": "{n} corrigés à vérifier",
  "afaire.corriges.texte": "Les réponses de l'exercice : le campus s'en sert pour noter.",
  "afaire.aRevoir.un": "1 copie à revoir",
  "afaire.aRevoir.n": "{n} copies à revoir",
  "afaire.aRevoir.texte": "Le campus vous laisse décider de la note.",
  "afaire.relectures.un": "1 étudiant demande une relecture",
  "afaire.relectures.n": "{n} étudiants demandent une relecture",
  "afaire.relectures.texte": "Gardez la note ou changez-la.",
  "afaire.copies.un": "1 copie à corriger",
  "afaire.copies.n": "{n} copies à corriger",
  "afaire.copies.texte": "Les copies de vos devoirs.",
  "afaire.aPublier.un": "1 note à envoyer",
  "afaire.aPublier.n": "{n} notes à envoyer",
  "afaire.aPublier.texte": "Vos étudiants la verront dès l'envoi.",
  "afaire.messages.un": "1 message non lu",
  "afaire.messages.n": "{n} messages non lus",
  "afaire.messages.texte": "Vos étudiants et la vie scolaire vous ont écrit.",
  "afaire.ouvrir": "Ouvrir",

  // ── Mes séances (accueil et /mes-seances) ──────────────────────────────────
  "seances.titre": "Mes séances",
  "seances.sousTitre": "Chaque cours que vous avez donné, et ce que le campus en a fait.",
  "seances.toutes": "Voir toutes mes séances",
  "seances.plus": "Voir plus de séances",
  "seances.fin": "C'est tout : vous avez vu toutes vos séances.",
  "seances.vide.titre": "Pas encore de séance",
  "seances.vide.texte": "Après votre premier cours, vous verrez ici la vidéo, le cours résumé, le QCM, l'exercice et les présents.",
  "seances.erreur": "Vos séances ne s'affichent pas pour l'instant.",
  "seances.tousCours": "Tous mes cours",
  "seances.cours": "Cours",

  // ── Liens simples en bas de l'accueil du formateur ─────────────────────────
  "liens.titre": "Aussi sur le campus",
  "liens.ecrire": "Écrire à mes étudiants",
  "liens.cours": "Mes cours",
  "liens.videos": "Vidéos des cours",
  "liens.emploi": "Mon emploi du temps",
  "liens.annonces": "Annonces",
  "liens.questions": "Questions en suspens",
  // Le manuel illustré du formateur (PDF, client/src/modules/manuels/manuels.ts) : en tête des liens.
  "liens.manuel": "Le manuel illustré",
  "liens.manuel.detail": "Le campus pas à pas, en images.",
  "liens.manuel.infos": "PDF · {pages} pages · {poids}",

  // ── Carte d'une séance (CarteSeance) ───────────────────────────────────────
  "carte.direct": "En direct",
  "carte.voir": "Voir la séance",
  "carte.avec": "avec {nom}",
  "etat.fait": "Fait",
  "etat.enCours": "En cours",
  "etat.pasEncore": "Pas encore",
  "video.titre": "Vidéo",
  "video.prete": "Prête",
  "video.preparation": "En préparation",
  "video.aucune": "Pas de vidéo",
  "video.vues.zero": "pas encore vue",
  "video.vues.un": "1 vue",
  "video.vues.n": "{n} vues",
  "resume.titre": "Cours résumé",
  "resume.prete": "Prêt",
  "resume.en_cours": "En préparation",
  "resume.a_venir": "Pas encore",
  "resume.erreur": "Nouvel essai",
  "resume.ouvert.zero": "pas encore ouvert",
  "resume.ouvert.un": "ouvert par 1",
  "resume.ouvert.n": "ouvert par {n}",
  "qcm.titre": "QCM",
  "qcm.aucun": "Pas de QCM",
  "qcm.faits": "{faits} / {sur}",
  "qcm.faits.detail": "l'ont fait",
  "qcm.moyenne": "moyenne {note}",
  "exercice.titre": "Exercice",
  "exercice.aucun": "Pas d'exercice",
  "exercice.copies.zero": "0 copie",
  "exercice.copies.un": "1 copie",
  "exercice.copies.n": "{n} copies",
  "exercice.notees.zero": "aucune notée",
  "exercice.notees.un": "1 notée",
  "exercice.notees.n": "{n} notées",
  "exercice.aRevoir.un": "1 à revoir",
  "exercice.aRevoir.n": "{n} à revoir",
  "exercice.corrige": "corrigé à vérifier",
  "presents.titre": "Présents",
  "presents.valeur": "{presents} / {attendus}",
  "presents.aucun": "Non comptés",
  "presents.inconnus.un": "1 non relevé",
  "presents.inconnus.n": "{n} non relevés",

  // ── Direction : « Le travail du campus » (/pilotage/travail) ───────────────
  "travail.menu": "Le travail du campus",
  "travail.menuCourt": "Le travail",
  "travail.etiquette": "Pilotage",
  "travail.titre": "Le travail du campus",
  "travail.sousTitre": "Les cours donnés et tout ce que le campus en a fait : vidéos, cours résumés, QCM, exercices, notes et présents.",
  "travail.periode": "Période",
  "travail.jours": "{n} jours",
  "travail.semaine": "Les 7 derniers jours",
  "travail.mois": "Les 30 derniers jours",
  "travail.seances": "Séances données",
  "travail.seances.detail": "présence {taux}",
  "travail.resumes": "Cours résumés",
  "travail.resumes.detail": "prêts pour les étudiants",
  "travail.envoyes": "QCM et exercices envoyés",
  "travail.envoyes.detail": "{qcm} · {exercices}",
  "travail.envoyes.qcm.un": "1 QCM",
  "travail.envoyes.qcm.n": "{n} QCM",
  "travail.envoyes.exercices.zero": "aucun exercice",
  "travail.envoyes.exercices.un": "1 exercice",
  "travail.envoyes.exercices.n": "{n} exercices",
  "travail.notees": "Copies d'exercice notées",
  "travail.notees.detail": "dont {campus} par le campus, sur {rendues} rendues",
  "travail.moyenne": "Moyenne des notes",
  "travail.moyenne.detail": "QCM et exercices, notes envoyées",
  "travail.moyenne.aucune": "pas encore de note",
  "travail.filtres": "Choisir",
  "travail.campus": "Campus",
  "travail.tousCampus": "Tous les campus",
  "travail.cours": "Cours",
  "travail.tousCours": "Tous les cours",
  "travail.formateur": "Formateur",
  "travail.tousFormateurs": "Tous les formateurs",
  "travail.fil": "Les séances, la plus récente d'abord",
  "travail.vide.titre": "Aucune séance pour ce choix",
  "travail.vide.texte": "Changez de campus, de cours ou de formateur, ou revenez après le prochain cours.",
  "travail.erreur": "Les chiffres ne s'affichent pas pour l'instant.",

  // ── Grande carte en tête de /pilotage ──────────────────────────────────────
  "tableau.carte.titre": "Voir tout le travail du campus",
  "tableau.carte.texte": "Séances, cours résumés, exercices, notes : tout ce qui a été fait, en un coup d'œil.",
  "tableau.carte.semaine": "Cette semaine : {seances} · {resumes} · {notees}",
  "tableau.carte.seances.un": "1 séance",
  "tableau.carte.seances.n": "{n} séances",
  "tableau.carte.resumes.un": "1 cours résumé",
  "tableau.carte.resumes.n": "{n} cours résumés",
  "tableau.carte.notees.un": "1 copie notée",
  "tableau.carte.notees.n": "{n} copies notées",
  "tableau.carte.bouton": "Voir le travail",
} satisfies Dictionnaire;

export type CleTravail = keyof typeof FR;
export const t = creerTextes(FR);

/** Choisit « .zero », « .un » ou « .n » selon le nombre, et passe {n}. */
export function selonNombre(tx: Traducteur<CleTravail>, base: string, n: number, options: OptionsTexte = {}): string {
  const v = { n, ...options.v };
  const suffixe = n === 0 && `${base}.zero` in FR ? "zero" : n === 1 ? "un" : "n";
  return tx(`${base}.${suffixe}` as CleTravail, { ...options, v });
}
